import terser from '@rollup/plugin-terser';
import copy from 'rollup-plugin-copy';
import { rmSync } from 'node:fs';
import { minify } from 'terser';

const ecma = 2022;
const npmThemes = [
  'dark',
  'github',
  'github-dark',
  'atom-one-light',
  'atom-one-dark',
];

const terserOptions = {
  ecma,
  module: true,
  compress: {
    ecma,
    module: true,
    passes: 3,
    pure_getters: true,
    toplevel: true,
  },
  mangle: false,
  format: {
    beautify: true,
    comments: false,
    indent_level: 2,
    preserve_annotations: false,
    semicolons: true,
  },
};

/**
 * Applies the final formatting rules for generated JavaScript files.
 *
 * The dist output is intentionally more compact than source code, but it stays
 * multi-line and readable enough for debugging an installed package.
 *
 * @param {string} code JavaScript code produced by Rollup or Terser.
 * @returns {string} Code with compact imports, TAB indentation, compact simple
 * object literals, no trailing whitespace, and at most one empty line in a row.
 *
 * @example
 * cleanCode('import a from "a";\n\nimport b from "b";\n')
 * // 'import a from "a";\nimport b from "b";\n'
 *
 * @example
 * cleanCode('  comment: {\\n    color: "#397300"\\n  }')
 * // 'comment: {color:"#397300"}\n'
 */
function cleanCode (code) {
  const codeWithTabs = compactImports(code).
    replace(/[ \t]+$/gm, '').
    replace(/^( {2})+/gm, (match) => '\t'.repeat(match.length / 2));

  return compactSimpleObjects(codeWithTabs).
    replace(/\n{3,}/g, '\n\n').
    trim().
    concat('\n');
}

/**
 * Removes empty lines between adjacent ESM import declarations.
 *
 * Terser can keep a blank line after each import when beautifying output.
 * For dist files, adjacent imports are more useful as one compact import block.
 *
 * @param {string} code JavaScript code.
 * @returns {string} JavaScript code without blank lines between adjacent imports.
 */
function compactImports (code) {
  return code.replace(/^(import .*;\n)\n(?=import )/gm, '$1');
}

/**
 * Compacts simple one-level object literals generated by Terser beautify.
 *
 * This is mostly for theme maps.
 * Terser expands entries such as `{ color: "#397300" }` into several lines.
 * This function brings those entries back to a dense single-line form while preserving one theme entry per line.
 * It intentionally skips nested object literals.
 *
 * @param {string} code JavaScript code with TAB indentation.
 * @returns {string} JavaScript code with simple objects compacted.
 *
 * @example
 * compactSimpleObjects('section: {\\n\\tbold: !0,\\n\\tcolor: "#880000"\\n}')
 * // 'section: {bold:!0,color:"#880000"}'
 */
function compactSimpleObjects (code) {
  return code.replace(/([,{]\n)(\t+)((?:"[^"]+"|[A-Za-z_$][\w$]*)): \{\n((?:\2\t[^\n{}]+,?\n)+)\2\}/g, (match, prefix, indent, key, body) => {
    const properties = body.
      split('\n').
      map((line) => line.trim()).
      filter(Boolean).
      map((line) => line.replace(/,$/, '')).
      map((line) => line.replace(/: /g, ':')).
      join(',');

    return `${prefix}${indent}${key}: {${properties}}`;
  });
}

/**
 * Minifies copied theme files with Terser, then applies the local dist format.
 *
 * Rollup only processes the main entry.
 * Theme files are copied into the NPM package, so they need a separate transform hook.
 *
 * @param {Buffer|string} contents Source file contents from rollup-plugin-copy.
 * @returns {Promise<string>} Optimized JavaScript code for a copied file.
 */
async function optimizeJs (contents) {
  const result = await minify(contents.toString(), terserOptions);

  return cleanCode(result.code);
}

/**
 * Formats copied JSON files for dist.
 *
 * The source JSON uses regular two-space indentation, while generated dist
 * files use TAB indentation. This is only applied to files copied into dist.
 *
 * @param {Buffer|string} contents JSON file contents from rollup-plugin-copy.
 * @returns {string} JSON with TAB indentation and one trailing newline.
 *
 * @example
 * cleanJson('{\n  "type": "module"\n}')
 * // '{\n\t"type": "module"\n}\n'
 */
function cleanJson (contents) {
  return contents.toString().replace(/^( {2})+/gm, (match) => '\t'.repeat(match.length / 2)).trim().concat('\n');
}

/**
 * Formats copied TypeScript declaration files for dist.
 *
 * The NPM declaration file should keep the public types but not the source
 * documentation comments.
 *
 * @param {Buffer|string} contents TypeScript declaration file contents from rollup-plugin-copy.
 * @returns {string} TypeScript declarations without comments, with TAB indentation and one trailing newline.
 */
function cleanDts (contents) {
  return contents.toString().
    replace(/\/\*[\s\S]*?\*\//g, '').
    replace(/[ \t]+$/gm, '').
    replace(/^( {4})+/gm, (match) => '\t'.repeat(match.length / 4)).
    replace(/\n\s*\n/g, '\n').
    trim().
    concat('\n');
}

/**
 * Creates a Rollup plugin that removes stale dist output before each build.
 *
 * This matters because only selected themes are copied to NPM.
 * Without cleanup, themes from an older build could remain in dist and accidentally get packed.
 *
 * @returns {import('rollup').Plugin} Rollup plugin.
 */
function cleanDist () {
  return {
    name: 'clean-dist',
    buildStart () {
      rmSync('dist', { recursive: true, force: true });
    },
  };
}

/**
 * Creates a Rollup plugin that applies final cleanup to generated chunks.
 *
 * Terser runs before this plugin.
 * This hook enforces project-specific dist formatting after Terser has optimized the code.
 *
 * @returns {import('rollup').Plugin} Rollup plugin.
 */
function cleanBundle () {
  return {
    name: 'clean-bundle',
    generateBundle (options, bundle) {
      for (const file of Object.values(bundle)) {
        if (file.type === 'chunk') {
          file.code = cleanCode(file.code);
        }
      }
    },
  };
}

export default {
  input: 'src/index.js',
  external: [
    'ansis',
    'highlight.js',
  ],
  output: {
    file: 'dist/index.js',
    format: 'esm',
    generatedCode: 'es2015',
  },
  plugins: [
    cleanDist(),
    terser(terserOptions),
    cleanBundle(),
    copy({
      targets: [
        {
          src: npmThemes.map((theme) => `themes/${theme}.js`),
          dest: 'dist/themes',
          transform: optimizeJs,
        },
        {
          src: 'package.npm.json',
          dest: 'dist',
          rename: 'package.json',
          transform: cleanJson,
        },
        {
          src: 'src/index.d.ts',
          dest: 'dist',
          rename: 'index.d.ts',
          transform: cleanDts,
        },
        {
          src: 'src/theme.d.ts',
          dest: 'dist',
          rename: 'theme.d.ts',
          transform: cleanDts,
        },
        {
          src: 'README.npm.md',
          dest: 'dist',
          rename: 'README.md',
        },
        {
          src: 'LICENSE',
          dest: 'dist',
        },
      ],
    }),
  ],
};
