// Generated from highlight.js/styles/a11y-dark.css.

export default {
  addition: { color: "#abe338" },
  attribute: { color: "#ffd700" },
  built_in: { color: "#f5ab35" },
  bullet: { color: "#abe338" },
  comment: { color: "#d4d0ab" },
  default: { background: "#2b2b2b", color: "#f8f8f2" },
  deletion: { color: "#ffa07a" },
  emphasis: { italic: true },
  keyword: { bold: true, color: "#dcc6e0" },
  link: { color: "#f5ab35" },
  literal: { color: "#f5ab35" },
  meta: { color: "#f5ab35" },
  name: { color: "#ffa07a" },
  number: { color: "#f5ab35" },
  params: { color: "#f5ab35" },
  quote: { color: "#d4d0ab" },
  regexp: { color: "#ffa07a" },
  section: { color: "#00e0e0" },
  "selector-class": { color: "#ffa07a" },
  "selector-id": { color: "#ffa07a" },
  "selector-tag": { bold: true, color: "#dcc6e0" },
  string: { color: "#abe338" },
  strong: { bold: true },
  symbol: { color: "#abe338" },
  tag: { color: "#ffa07a" },
  "template-variable": { color: "#ffa07a" },
  title: { color: "#00e0e0" },
  type: { color: "#f5ab35" },
  variable: { color: "#ffa07a" },
};
