// Generated from highlight.js/styles/agate.css.

export default {
  addition: { background: "#a2fca2", color: "#333" },
  attr: { color: "#7bd694" },
  attribute: { color: "#ffa" },
  built_in: { color: "#fcc28c" },
  bullet: { color: "#b8d8a2" },
  code: { color: "#888", italic: true },
  comment: { color: "#888" },
  default: { background: "#333", color: "#fff" },
  deletion: { background: "#fc9b9b", color: "#333" },
  doctag: { bold: true },
  emphasis: { italic: true },
  formula: { color: "#888" },
  keyword: { color: "#fcc28c" },
  link: { color: "#c6b4f0" },
  literal: { color: "#fcc28c" },
  meta: { color: "#fc9b9b" },
  "meta-keyword": { bold: true },
  "meta-string": { color: "#a2fca2" },
  name: { bold: true },
  number: { color: "#d36363" },
  quote: { color: "#7bd694" },
  regexp: { color: "#c6b4f0" },
  section: { color: "#62c8f3" },
  "selector-attr": { color: "#7bd694" },
  "selector-class": { color: "#ade5fc" },
  "selector-id": { color: "#ade5fc" },
  "selector-pseudo": { color: "#c6b4f0" },
  "selector-tag": { color: "#fcc28c" },
  string: { color: "#a2fca2" },
  strong: { bold: true },
  subst: { color: "#fff" },
  symbol: { color: "#d36363" },
  tag: { color: "#62c8f3" },
  "template-tag": { color: "#b8d8a2" },
  "template-variable": { color: "#ade5fc" },
  title: { color: "#ffa" },
  type: { color: "#ffa" },
  variable: { color: "#ade5fc" },
};
