// Generated from highlight.js/styles/arta.css.

export default {
  addition: { color: "#00cc66" },
  attribute: { color: "#32aaee" },
  built_in: { color: "#32aaee" },
  bullet: { color: "#ffcc33" },
  comment: { color: "#444" },
  default: { background: "#222", color: "#aaa" },
  deletion: { color: "#bb1166" },
  doctag: { bold: true },
  emphasis: { italic: true },
  keyword: { color: "#6644aa" },
  link: { color: "#32aaee" },
  literal: { color: "#32aaee" },
  meta: { color: "#444" },
  name: { color: "#6644aa" },
  number: { color: "#00cc66" },
  quote: { color: "#444" },
  regexp: { color: "#ffcc33" },
  section: { bold: true, color: "#fff" },
  "selector-class": { color: "#6644aa" },
  "selector-id": { color: "#6644aa" },
  "selector-tag": { color: "#6644aa" },
  string: { color: "#ffcc33" },
  strong: { bold: true },
  subst: { color: "#aaa" },
  symbol: { color: "#ffcc33" },
  "template-tag": { color: "#bb1166" },
  "template-variable": { color: "#32aaee" },
  title: { color: "#bb1166" },
  type: { color: "#32aaee" },
  variable: { color: "#bb1166" },
};
