// Generated from highlight.js/styles/base16/pop.css.

export default {
  addition: { color: "#37b349" },
  attr: { color: "#f29333" },
  attribute: { color: "#0e5a94" },
  built_in: { color: "#00aabb" },
  bullet: { color: "#eb008a" },
  "class title": { color: "#f8ca12" },
  code: { color: "#37b349" },
  comment: { color: "#505050" },
  default: { background: "#000000", color: "#d0d0d0" },
  deletion: { color: "#eb008a" },
  doctag: { color: "#00aabb" },
  emphasis: { color: "#b31e8d", italic: true },
  "function title": { color: "#0e5a94" },
  keyword: { color: "#b31e8d" },
  "keyword.atrule": { color: "#00aabb" },
  link: { color: "#f29333" },
  literal: { color: "#f29333" },
  meta: { color: "#7a2d00" },
  "meta keyword": { bold: true, color: "#7a2d00" },
  "meta string": { color: "#7a2d00" },
  "meta-keyword": { bold: true },
  name: { color: "#eb008a" },
  number: { color: "#f29333" },
  operator: { color: "#d0d0d0" },
  punctuation: { color: "#d0d0d0" },
  quote: { color: "#00aabb" },
  regexp: { color: "#00aabb" },
  section: { color: "#0e5a94" },
  "selector-tag": { color: "#eb008a" },
  string: { color: "#37b349" },
  strong: { bold: true, color: "#f8ca12" },
  subst: { color: "#d0d0d0" },
  symbol: { color: "#f29333" },
  tag: { color: "#b0b0b0" },
  "template-tag": { color: "#b31e8d" },
  "template-variable": { color: "#eb008a" },
  title: { color: "#f8ca12" },
  "title.class": { color: "#f8ca12" },
  "title.class.inherited": { color: "#37b349" },
  "title.function": { color: "#0e5a94" },
  type: { color: "#b31e8d" },
  variable: { color: "#eb008a" },
  "variable.constant": { color: "#f29333" },
};
