// Generated from highlight.js/styles/base16/nova.css.

export default {
  addition: { color: "#7FC1CA" },
  attr: { color: "#7FC1CA" },
  attribute: { color: "#83AFE5" },
  built_in: { color: "#F2C38F" },
  bullet: { color: "#83AFE5" },
  "class title": { color: "#A8CE93" },
  code: { color: "#7FC1CA" },
  comment: { color: "#899BA6" },
  default: { background: "#3C4C55", color: "#C5D4DD" },
  deletion: { color: "#83AFE5" },
  doctag: { color: "#F2C38F" },
  emphasis: { color: "#9A93E1", italic: true },
  "function title": { color: "#83AFE5" },
  keyword: { color: "#9A93E1" },
  "keyword.atrule": { color: "#F2C38F" },
  link: { color: "#7FC1CA" },
  literal: { color: "#7FC1CA" },
  meta: { color: "#F2C38F" },
  "meta keyword": { bold: true, color: "#F2C38F" },
  "meta string": { color: "#F2C38F" },
  "meta-keyword": { bold: true },
  name: { color: "#83AFE5" },
  number: { color: "#7FC1CA" },
  operator: { color: "#C5D4DD" },
  punctuation: { color: "#C5D4DD" },
  quote: { color: "#F2C38F" },
  regexp: { color: "#F2C38F" },
  section: { color: "#83AFE5" },
  "selector-tag": { color: "#83AFE5" },
  string: { color: "#7FC1CA" },
  strong: { bold: true, color: "#A8CE93" },
  subst: { color: "#C5D4DD" },
  symbol: { color: "#7FC1CA" },
  tag: { color: "#899BA6" },
  "template-tag": { color: "#9A93E1" },
  "template-variable": { color: "#83AFE5" },
  title: { color: "#A8CE93" },
  "title.class": { color: "#A8CE93" },
  "title.class.inherited": { color: "#7FC1CA" },
  "title.function": { color: "#83AFE5" },
  type: { color: "#9A93E1" },
  variable: { color: "#83AFE5" },
  "variable.constant": { color: "#7FC1CA" },
};
