// Generated from highlight.js/styles/base16/ia-dark.css.

export default {
  addition: { color: "#83a471" },
  attr: { color: "#d86868" },
  attribute: { color: "#8eccdd" },
  built_in: { color: "#7c9cae" },
  bullet: { color: "#d88568" },
  "class title": { color: "#b99353" },
  code: { color: "#83a471" },
  comment: { color: "#767676" },
  default: { background: "#1a1a1a", color: "#cccccc" },
  deletion: { color: "#d88568" },
  doctag: { color: "#7c9cae" },
  emphasis: { color: "#b98eb2", italic: true },
  "function title": { color: "#8eccdd" },
  keyword: { color: "#b98eb2" },
  "keyword.atrule": { color: "#7c9cae" },
  link: { color: "#d86868" },
  literal: { color: "#d86868" },
  meta: { color: "#8b6c37" },
  "meta keyword": { bold: true, color: "#8b6c37" },
  "meta string": { color: "#8b6c37" },
  "meta-keyword": { bold: true },
  name: { color: "#d88568" },
  number: { color: "#d86868" },
  operator: { color: "#cccccc" },
  punctuation: { color: "#cccccc" },
  quote: { color: "#7c9cae" },
  regexp: { color: "#7c9cae" },
  section: { color: "#8eccdd" },
  "selector-tag": { color: "#d88568" },
  string: { color: "#83a471" },
  strong: { bold: true, color: "#b99353" },
  subst: { color: "#cccccc" },
  symbol: { color: "#d86868" },
  tag: { color: "#b8b8b8" },
  "template-tag": { color: "#b98eb2" },
  "template-variable": { color: "#d88568" },
  title: { color: "#b99353" },
  "title.class": { color: "#b99353" },
  "title.class.inherited": { color: "#83a471" },
  "title.function": { color: "#8eccdd" },
  type: { color: "#b98eb2" },
  variable: { color: "#d88568" },
  "variable.constant": { color: "#d86868" },
};
