// Generated from highlight.js/styles/base16/helios.css.

export default {
  addition: { color: "#88b92d" },
  attr: { color: "#eb8413" },
  attribute: { color: "#1e8bac" },
  built_in: { color: "#1ba595" },
  bullet: { color: "#d72638" },
  "class title": { color: "#f19d1a" },
  code: { color: "#88b92d" },
  comment: { color: "#6f7579" },
  default: { background: "#1d2021", color: "#d5d5d5" },
  deletion: { color: "#d72638" },
  doctag: { color: "#1ba595" },
  emphasis: { color: "#be4264", italic: true },
  "function title": { color: "#1e8bac" },
  keyword: { color: "#be4264" },
  "keyword.atrule": { color: "#1ba595" },
  link: { color: "#eb8413" },
  literal: { color: "#eb8413" },
  meta: { color: "#c85e0d" },
  "meta keyword": { bold: true, color: "#c85e0d" },
  "meta string": { color: "#c85e0d" },
  "meta-keyword": { bold: true },
  name: { color: "#d72638" },
  number: { color: "#eb8413" },
  operator: { color: "#d5d5d5" },
  punctuation: { color: "#d5d5d5" },
  quote: { color: "#1ba595" },
  regexp: { color: "#1ba595" },
  section: { color: "#1e8bac" },
  "selector-tag": { color: "#d72638" },
  string: { color: "#88b92d" },
  strong: { bold: true, color: "#f19d1a" },
  subst: { color: "#d5d5d5" },
  symbol: { color: "#eb8413" },
  tag: { color: "#cdcdcd" },
  "template-tag": { color: "#be4264" },
  "template-variable": { color: "#d72638" },
  title: { color: "#f19d1a" },
  "title.class": { color: "#f19d1a" },
  "title.class.inherited": { color: "#88b92d" },
  "title.function": { color: "#1e8bac" },
  type: { color: "#be4264" },
  variable: { color: "#d72638" },
  "variable.constant": { color: "#eb8413" },
};
