// Generated from highlight.js/styles/base16/chalk.css.

export default {
  addition: { color: "#acc267" },
  attr: { color: "#eda987" },
  attribute: { color: "#6fc2ef" },
  built_in: { color: "#12cfc0" },
  bullet: { color: "#fb9fb1" },
  "class title": { color: "#ddb26f" },
  code: { color: "#acc267" },
  comment: { color: "#505050" },
  default: { background: "#151515", color: "#d0d0d0" },
  deletion: { color: "#fb9fb1" },
  doctag: { color: "#12cfc0" },
  emphasis: { color: "#e1a3ee", italic: true },
  "function title": { color: "#6fc2ef" },
  keyword: { color: "#e1a3ee" },
  "keyword.atrule": { color: "#12cfc0" },
  link: { color: "#eda987" },
  literal: { color: "#eda987" },
  meta: { color: "#deaf8f" },
  "meta keyword": { bold: true, color: "#deaf8f" },
  "meta string": { color: "#deaf8f" },
  "meta-keyword": { bold: true },
  name: { color: "#fb9fb1" },
  number: { color: "#eda987" },
  operator: { color: "#d0d0d0" },
  punctuation: { color: "#d0d0d0" },
  quote: { color: "#12cfc0" },
  regexp: { color: "#12cfc0" },
  section: { color: "#6fc2ef" },
  "selector-tag": { color: "#fb9fb1" },
  string: { color: "#acc267" },
  strong: { bold: true, color: "#ddb26f" },
  subst: { color: "#d0d0d0" },
  symbol: { color: "#eda987" },
  tag: { color: "#b0b0b0" },
  "template-tag": { color: "#e1a3ee" },
  "template-variable": { color: "#fb9fb1" },
  title: { color: "#ddb26f" },
  "title.class": { color: "#ddb26f" },
  "title.class.inherited": { color: "#acc267" },
  "title.function": { color: "#6fc2ef" },
  type: { color: "#e1a3ee" },
  variable: { color: "#fb9fb1" },
  "variable.constant": { color: "#eda987" },
};
