// Generated from highlight.js/styles/base16/ocean.css.

export default {
  addition: { color: "#a3be8c" },
  attr: { color: "#d08770" },
  attribute: { color: "#8fa1b3" },
  built_in: { color: "#96b5b4" },
  bullet: { color: "#bf616a" },
  "class title": { color: "#ebcb8b" },
  code: { color: "#a3be8c" },
  comment: { color: "#65737e" },
  default: { background: "#2b303b", color: "#c0c5ce" },
  deletion: { color: "#bf616a" },
  doctag: { color: "#96b5b4" },
  emphasis: { color: "#b48ead", italic: true },
  "function title": { color: "#8fa1b3" },
  keyword: { color: "#b48ead" },
  "keyword.atrule": { color: "#96b5b4" },
  link: { color: "#d08770" },
  literal: { color: "#d08770" },
  meta: { color: "#ab7967" },
  "meta keyword": { bold: true, color: "#ab7967" },
  "meta string": { color: "#ab7967" },
  "meta-keyword": { bold: true },
  name: { color: "#bf616a" },
  number: { color: "#d08770" },
  operator: { color: "#c0c5ce" },
  punctuation: { color: "#c0c5ce" },
  quote: { color: "#96b5b4" },
  regexp: { color: "#96b5b4" },
  section: { color: "#8fa1b3" },
  "selector-tag": { color: "#bf616a" },
  string: { color: "#a3be8c" },
  strong: { bold: true, color: "#ebcb8b" },
  subst: { color: "#c0c5ce" },
  symbol: { color: "#d08770" },
  tag: { color: "#a7adba" },
  "template-tag": { color: "#b48ead" },
  "template-variable": { color: "#bf616a" },
  title: { color: "#ebcb8b" },
  "title.class": { color: "#ebcb8b" },
  "title.class.inherited": { color: "#a3be8c" },
  "title.function": { color: "#8fa1b3" },
  type: { color: "#b48ead" },
  variable: { color: "#bf616a" },
  "variable.constant": { color: "#d08770" },
};
