// Generated from highlight.js/styles/base16/nord.css.

export default {
  addition: { color: "#A3BE8C" },
  attr: { color: "#D08770" },
  attribute: { color: "#81A1C1" },
  built_in: { color: "#88C0D0" },
  bullet: { color: "#BF616A" },
  "class title": { color: "#EBCB8B" },
  code: { color: "#A3BE8C" },
  comment: { color: "#4C566A" },
  default: { background: "#2E3440", color: "#E5E9F0" },
  deletion: { color: "#BF616A" },
  doctag: { color: "#88C0D0" },
  emphasis: { color: "#B48EAD", italic: true },
  "function title": { color: "#81A1C1" },
  keyword: { color: "#B48EAD" },
  "keyword.atrule": { color: "#88C0D0" },
  link: { color: "#D08770" },
  literal: { color: "#D08770" },
  meta: { color: "#5E81AC" },
  "meta keyword": { bold: true, color: "#5E81AC" },
  "meta string": { color: "#5E81AC" },
  "meta-keyword": { bold: true },
  name: { color: "#BF616A" },
  number: { color: "#D08770" },
  operator: { color: "#E5E9F0" },
  punctuation: { color: "#E5E9F0" },
  quote: { color: "#88C0D0" },
  regexp: { color: "#88C0D0" },
  section: { color: "#81A1C1" },
  "selector-tag": { color: "#BF616A" },
  string: { color: "#A3BE8C" },
  strong: { bold: true, color: "#EBCB8B" },
  subst: { color: "#E5E9F0" },
  symbol: { color: "#D08770" },
  tag: { color: "#D8DEE9" },
  "template-tag": { color: "#B48EAD" },
  "template-variable": { color: "#BF616A" },
  title: { color: "#EBCB8B" },
  "title.class": { color: "#EBCB8B" },
  "title.class.inherited": { color: "#A3BE8C" },
  "title.function": { color: "#81A1C1" },
  type: { color: "#B48EAD" },
  variable: { color: "#BF616A" },
  "variable.constant": { color: "#D08770" },
};
