// Generated from highlight.js/styles/base16/seti-ui.css.

export default {
  addition: { color: "#9fca56" },
  attr: { color: "#db7b55" },
  attribute: { color: "#55b5db" },
  built_in: { color: "#55dbbe" },
  bullet: { color: "#Cd3f45" },
  "class title": { color: "#e6cd69" },
  code: { color: "#9fca56" },
  comment: { color: "#41535B" },
  default: { background: "#151718", color: "#d6d6d6" },
  deletion: { color: "#Cd3f45" },
  doctag: { color: "#55dbbe" },
  emphasis: { color: "#a074c4", italic: true },
  "function title": { color: "#55b5db" },
  keyword: { color: "#a074c4" },
  "keyword.atrule": { color: "#55dbbe" },
  link: { color: "#db7b55" },
  literal: { color: "#db7b55" },
  meta: { color: "#8a553f" },
  "meta keyword": { bold: true, color: "#8a553f" },
  "meta string": { color: "#8a553f" },
  "meta-keyword": { bold: true },
  name: { color: "#Cd3f45" },
  number: { color: "#db7b55" },
  operator: { color: "#d6d6d6" },
  punctuation: { color: "#d6d6d6" },
  quote: { color: "#55dbbe" },
  regexp: { color: "#55dbbe" },
  section: { color: "#55b5db" },
  "selector-tag": { color: "#Cd3f45" },
  string: { color: "#9fca56" },
  strong: { bold: true, color: "#e6cd69" },
  subst: { color: "#d6d6d6" },
  symbol: { color: "#db7b55" },
  tag: { color: "#43a5d5" },
  "template-tag": { color: "#a074c4" },
  "template-variable": { color: "#Cd3f45" },
  title: { color: "#e6cd69" },
  "title.class": { color: "#e6cd69" },
  "title.class.inherited": { color: "#9fca56" },
  "title.function": { color: "#55b5db" },
  type: { color: "#a074c4" },
  variable: { color: "#Cd3f45" },
  "variable.constant": { color: "#db7b55" },
};
