// Generated from highlight.js/styles/base16/dracula.css.

export default {
  addition: { color: "#ebff87" },
  attr: { color: "#b45bcf" },
  attribute: { color: "#62d6e8" },
  built_in: { color: "#a1efe4" },
  bullet: { color: "#ea51b2" },
  "class title": { color: "#00f769" },
  code: { color: "#ebff87" },
  comment: { color: "#626483" },
  default: { background: "#282936", color: "#e9e9f4" },
  deletion: { color: "#ea51b2" },
  doctag: { color: "#a1efe4" },
  emphasis: { color: "#b45bcf", italic: true },
  "function title": { color: "#62d6e8" },
  keyword: { color: "#b45bcf" },
  "keyword.atrule": { color: "#a1efe4" },
  link: { color: "#b45bcf" },
  literal: { color: "#b45bcf" },
  meta: { color: "#00f769" },
  "meta keyword": { bold: true, color: "#00f769" },
  "meta string": { color: "#00f769" },
  "meta-keyword": { bold: true },
  name: { color: "#ea51b2" },
  number: { color: "#b45bcf" },
  operator: { color: "#e9e9f4" },
  punctuation: { color: "#e9e9f4" },
  quote: { color: "#a1efe4" },
  regexp: { color: "#a1efe4" },
  section: { color: "#62d6e8" },
  "selector-tag": { color: "#ea51b2" },
  string: { color: "#ebff87" },
  strong: { bold: true, color: "#00f769" },
  subst: { color: "#e9e9f4" },
  symbol: { color: "#b45bcf" },
  tag: { color: "#62d6e8" },
  "template-tag": { color: "#b45bcf" },
  "template-variable": { color: "#ea51b2" },
  title: { color: "#00f769" },
  "title.class": { color: "#00f769" },
  "title.class.inherited": { color: "#ebff87" },
  "title.function": { color: "#62d6e8" },
  type: { color: "#b45bcf" },
  variable: { color: "#ea51b2" },
  "variable.constant": { color: "#b45bcf" },
};
