// Generated from highlight.js/styles/base16/mocha.css.

export default {
  addition: { color: "#beb55b" },
  attr: { color: "#d28b71" },
  attribute: { color: "#8ab3b5" },
  built_in: { color: "#7bbda4" },
  bullet: { color: "#cb6077" },
  "class title": { color: "#f4bc87" },
  code: { color: "#beb55b" },
  comment: { color: "#7e705a" },
  default: { background: "#3B3228", color: "#d0c8c6" },
  deletion: { color: "#cb6077" },
  doctag: { color: "#7bbda4" },
  emphasis: { color: "#a89bb9", italic: true },
  "function title": { color: "#8ab3b5" },
  keyword: { color: "#a89bb9" },
  "keyword.atrule": { color: "#7bbda4" },
  link: { color: "#d28b71" },
  literal: { color: "#d28b71" },
  meta: { color: "#bb9584" },
  "meta keyword": { bold: true, color: "#bb9584" },
  "meta string": { color: "#bb9584" },
  "meta-keyword": { bold: true },
  name: { color: "#cb6077" },
  number: { color: "#d28b71" },
  operator: { color: "#d0c8c6" },
  punctuation: { color: "#d0c8c6" },
  quote: { color: "#7bbda4" },
  regexp: { color: "#7bbda4" },
  section: { color: "#8ab3b5" },
  "selector-tag": { color: "#cb6077" },
  string: { color: "#beb55b" },
  strong: { bold: true, color: "#f4bc87" },
  subst: { color: "#d0c8c6" },
  symbol: { color: "#d28b71" },
  tag: { color: "#b8afad" },
  "template-tag": { color: "#a89bb9" },
  "template-variable": { color: "#cb6077" },
  title: { color: "#f4bc87" },
  "title.class": { color: "#f4bc87" },
  "title.class.inherited": { color: "#beb55b" },
  "title.function": { color: "#8ab3b5" },
  type: { color: "#a89bb9" },
  variable: { color: "#cb6077" },
  "variable.constant": { color: "#d28b71" },
};
