// Generated from highlight.js/styles/base16/snazzy.css.

export default {
  addition: { color: "#5af78e" },
  attr: { color: "#ff9f43" },
  attribute: { color: "#57c7ff" },
  built_in: { color: "#9aedfe" },
  bullet: { color: "#ff5c57" },
  "class title": { color: "#f3f99d" },
  code: { color: "#5af78e" },
  comment: { color: "#78787e" },
  default: { background: "#282a36", color: "#e2e4e5" },
  deletion: { color: "#ff5c57" },
  doctag: { color: "#9aedfe" },
  emphasis: { color: "#ff6ac1", italic: true },
  "function title": { color: "#57c7ff" },
  keyword: { color: "#ff6ac1" },
  "keyword.atrule": { color: "#9aedfe" },
  link: { color: "#ff9f43" },
  literal: { color: "#ff9f43" },
  meta: { color: "#b2643c" },
  "meta keyword": { bold: true, color: "#b2643c" },
  "meta string": { color: "#b2643c" },
  "meta-keyword": { bold: true },
  name: { color: "#ff5c57" },
  number: { color: "#ff9f43" },
  operator: { color: "#e2e4e5" },
  punctuation: { color: "#e2e4e5" },
  quote: { color: "#9aedfe" },
  regexp: { color: "#9aedfe" },
  section: { color: "#57c7ff" },
  "selector-tag": { color: "#ff5c57" },
  string: { color: "#5af78e" },
  strong: { bold: true, color: "#f3f99d" },
  subst: { color: "#e2e4e5" },
  symbol: { color: "#ff9f43" },
  tag: { color: "#a5a5a9" },
  "template-tag": { color: "#ff6ac1" },
  "template-variable": { color: "#ff5c57" },
  title: { color: "#f3f99d" },
  "title.class": { color: "#f3f99d" },
  "title.class.inherited": { color: "#5af78e" },
  "title.function": { color: "#57c7ff" },
  type: { color: "#ff6ac1" },
  variable: { color: "#ff5c57" },
  "variable.constant": { color: "#ff9f43" },
};
