// Generated from highlight.js/styles/base16/bright.css.

export default {
  addition: { color: "#a1c659" },
  attr: { color: "#fc6d24" },
  attribute: { color: "#6fb3d2" },
  built_in: { color: "#76c7b7" },
  bullet: { color: "#fb0120" },
  "class title": { color: "#fda331" },
  code: { color: "#a1c659" },
  comment: { color: "#b0b0b0" },
  default: { background: "#000000", color: "#e0e0e0" },
  deletion: { color: "#fb0120" },
  doctag: { color: "#76c7b7" },
  emphasis: { color: "#d381c3", italic: true },
  "function title": { color: "#6fb3d2" },
  keyword: { color: "#d381c3" },
  "keyword.atrule": { color: "#76c7b7" },
  link: { color: "#fc6d24" },
  literal: { color: "#fc6d24" },
  meta: { color: "#be643c" },
  "meta keyword": { bold: true, color: "#be643c" },
  "meta string": { color: "#be643c" },
  "meta-keyword": { bold: true },
  name: { color: "#fb0120" },
  number: { color: "#fc6d24" },
  operator: { color: "#e0e0e0" },
  punctuation: { color: "#e0e0e0" },
  quote: { color: "#76c7b7" },
  regexp: { color: "#76c7b7" },
  section: { color: "#6fb3d2" },
  "selector-tag": { color: "#fb0120" },
  string: { color: "#a1c659" },
  strong: { bold: true, color: "#fda331" },
  subst: { color: "#e0e0e0" },
  symbol: { color: "#fc6d24" },
  tag: { color: "#d0d0d0" },
  "template-tag": { color: "#d381c3" },
  "template-variable": { color: "#fb0120" },
  title: { color: "#fda331" },
  "title.class": { color: "#fda331" },
  "title.class.inherited": { color: "#a1c659" },
  "title.function": { color: "#6fb3d2" },
  type: { color: "#d381c3" },
  variable: { color: "#fb0120" },
  "variable.constant": { color: "#fc6d24" },
};
