// Generated from highlight.js/styles/base16/pico.css.

export default {
  addition: { color: "#00e756" },
  attr: { color: "#ffa300" },
  attribute: { color: "#83769c" },
  built_in: { color: "#29adff" },
  bullet: { color: "#ff004d" },
  "class title": { color: "#fff024" },
  code: { color: "#00e756" },
  comment: { color: "#008751" },
  default: { background: "#000000", color: "#5f574f" },
  deletion: { color: "#ff004d" },
  doctag: { color: "#29adff" },
  emphasis: { color: "#ff77a8", italic: true },
  "function title": { color: "#83769c" },
  keyword: { color: "#ff77a8" },
  "keyword.atrule": { color: "#29adff" },
  link: { color: "#ffa300" },
  literal: { color: "#ffa300" },
  meta: { color: "#ffccaa" },
  "meta keyword": { bold: true, color: "#ffccaa" },
  "meta string": { color: "#ffccaa" },
  "meta-keyword": { bold: true },
  name: { color: "#ff004d" },
  number: { color: "#ffa300" },
  operator: { color: "#5f574f" },
  punctuation: { color: "#5f574f" },
  quote: { color: "#29adff" },
  regexp: { color: "#29adff" },
  section: { color: "#83769c" },
  "selector-tag": { color: "#ff004d" },
  string: { color: "#00e756" },
  strong: { bold: true, color: "#fff024" },
  subst: { color: "#5f574f" },
  symbol: { color: "#ffa300" },
  tag: { color: "#ab5236" },
  "template-tag": { color: "#ff77a8" },
  "template-variable": { color: "#ff004d" },
  title: { color: "#fff024" },
  "title.class": { color: "#fff024" },
  "title.class.inherited": { color: "#00e756" },
  "title.function": { color: "#83769c" },
  type: { color: "#ff77a8" },
  variable: { color: "#ff004d" },
  "variable.constant": { color: "#ffa300" },
};
