// Generated from highlight.js/styles/base16/ashes.css.

export default {
  addition: { color: "#95C7AE" },
  attr: { color: "#C7C795" },
  attribute: { color: "#AE95C7" },
  built_in: { color: "#95AEC7" },
  bullet: { color: "#C7AE95" },
  "class title": { color: "#AEC795" },
  code: { color: "#95C7AE" },
  comment: { color: "#747C84" },
  default: { background: "#1C2023", color: "#C7CCD1" },
  deletion: { color: "#C7AE95" },
  doctag: { color: "#95AEC7" },
  emphasis: { color: "#C795AE", italic: true },
  "function title": { color: "#AE95C7" },
  keyword: { color: "#C795AE" },
  "keyword.atrule": { color: "#95AEC7" },
  link: { color: "#C7C795" },
  literal: { color: "#C7C795" },
  meta: { color: "#C79595" },
  "meta keyword": { bold: true, color: "#C79595" },
  "meta string": { color: "#C79595" },
  "meta-keyword": { bold: true },
  name: { color: "#C7AE95" },
  number: { color: "#C7C795" },
  operator: { color: "#C7CCD1" },
  punctuation: { color: "#C7CCD1" },
  quote: { color: "#95AEC7" },
  regexp: { color: "#95AEC7" },
  section: { color: "#AE95C7" },
  "selector-tag": { color: "#C7AE95" },
  string: { color: "#95C7AE" },
  strong: { bold: true, color: "#AEC795" },
  subst: { color: "#C7CCD1" },
  symbol: { color: "#C7C795" },
  tag: { color: "#ADB3BA" },
  "template-tag": { color: "#C795AE" },
  "template-variable": { color: "#C7AE95" },
  title: { color: "#AEC795" },
  "title.class": { color: "#AEC795" },
  "title.class.inherited": { color: "#95C7AE" },
  "title.function": { color: "#AE95C7" },
  type: { color: "#C795AE" },
  variable: { color: "#C7AE95" },
  "variable.constant": { color: "#C7C795" },
};
