// Generated from highlight.js/styles/base16/eva.css.

export default {
  addition: { color: "#66ff66" },
  attr: { color: "#ff9966" },
  attribute: { color: "#15f4ee" },
  built_in: { color: "#4b8f77" },
  bullet: { color: "#c4676c" },
  "class title": { color: "#ffff66" },
  code: { color: "#66ff66" },
  comment: { color: "#55799c" },
  default: { background: "#2a3b4d", color: "#9fa2a6" },
  deletion: { color: "#c4676c" },
  doctag: { color: "#4b8f77" },
  emphasis: { color: "#9c6cd3", italic: true },
  "function title": { color: "#15f4ee" },
  keyword: { color: "#9c6cd3" },
  "keyword.atrule": { color: "#4b8f77" },
  link: { color: "#ff9966" },
  literal: { color: "#ff9966" },
  meta: { color: "#bb64a9" },
  "meta keyword": { bold: true, color: "#bb64a9" },
  "meta string": { color: "#bb64a9" },
  "meta-keyword": { bold: true },
  name: { color: "#c4676c" },
  number: { color: "#ff9966" },
  operator: { color: "#9fa2a6" },
  punctuation: { color: "#9fa2a6" },
  quote: { color: "#4b8f77" },
  regexp: { color: "#4b8f77" },
  section: { color: "#15f4ee" },
  "selector-tag": { color: "#c4676c" },
  string: { color: "#66ff66" },
  strong: { bold: true, color: "#ffff66" },
  subst: { color: "#9fa2a6" },
  symbol: { color: "#ff9966" },
  tag: { color: "#7e90a3" },
  "template-tag": { color: "#9c6cd3" },
  "template-variable": { color: "#c4676c" },
  title: { color: "#ffff66" },
  "title.class": { color: "#ffff66" },
  "title.class.inherited": { color: "#66ff66" },
  "title.function": { color: "#15f4ee" },
  type: { color: "#9c6cd3" },
  variable: { color: "#c4676c" },
  "variable.constant": { color: "#ff9966" },
};
