// Generated from highlight.js/styles/base16/decaf.css.

export default {
  addition: { color: "#beda78" },
  attr: { color: "#ffbf70" },
  attribute: { color: "#90bee1" },
  built_in: { color: "#bed6ff" },
  bullet: { color: "#ff7f7b" },
  "class title": { color: "#ffd67c" },
  code: { color: "#beda78" },
  comment: { color: "#777777" },
  default: { background: "#2d2d2d", color: "#cccccc" },
  deletion: { color: "#ff7f7b" },
  doctag: { color: "#bed6ff" },
  emphasis: { color: "#efb3f7", italic: true },
  "function title": { color: "#90bee1" },
  keyword: { color: "#efb3f7" },
  "keyword.atrule": { color: "#bed6ff" },
  link: { color: "#ffbf70" },
  literal: { color: "#ffbf70" },
  meta: { color: "#ff93b3" },
  "meta keyword": { bold: true, color: "#ff93b3" },
  "meta string": { color: "#ff93b3" },
  "meta-keyword": { bold: true },
  name: { color: "#ff7f7b" },
  number: { color: "#ffbf70" },
  operator: { color: "#cccccc" },
  punctuation: { color: "#cccccc" },
  quote: { color: "#bed6ff" },
  regexp: { color: "#bed6ff" },
  section: { color: "#90bee1" },
  "selector-tag": { color: "#ff7f7b" },
  string: { color: "#beda78" },
  strong: { bold: true, color: "#ffd67c" },
  subst: { color: "#cccccc" },
  symbol: { color: "#ffbf70" },
  tag: { color: "#b4b7b4" },
  "template-tag": { color: "#efb3f7" },
  "template-variable": { color: "#ff7f7b" },
  title: { color: "#ffd67c" },
  "title.class": { color: "#ffd67c" },
  "title.class.inherited": { color: "#beda78" },
  "title.function": { color: "#90bee1" },
  type: { color: "#efb3f7" },
  variable: { color: "#ff7f7b" },
  "variable.constant": { color: "#ffbf70" },
};
