// Generated from highlight.js/styles/base16/cupcake.css.

export default {
  addition: { color: "#A3B367" },
  attr: { color: "#EBB790" },
  attribute: { color: "#7297B9" },
  built_in: { color: "#69A9A7" },
  bullet: { color: "#D57E85" },
  "class title": { color: "#DCB16C" },
  code: { color: "#A3B367" },
  comment: { color: "#bfb9c6" },
  default: { background: "#fbf1f2", color: "#8b8198" },
  deletion: { color: "#D57E85" },
  doctag: { color: "#69A9A7" },
  emphasis: { color: "#BB99B4", italic: true },
  "function title": { color: "#7297B9" },
  keyword: { color: "#BB99B4" },
  "keyword.atrule": { color: "#69A9A7" },
  link: { color: "#EBB790" },
  literal: { color: "#EBB790" },
  meta: { color: "#BAA58C" },
  "meta keyword": { bold: true, color: "#BAA58C" },
  "meta string": { color: "#BAA58C" },
  "meta-keyword": { bold: true },
  name: { color: "#D57E85" },
  number: { color: "#EBB790" },
  operator: { color: "#8b8198" },
  punctuation: { color: "#8b8198" },
  quote: { color: "#69A9A7" },
  regexp: { color: "#69A9A7" },
  section: { color: "#7297B9" },
  "selector-tag": { color: "#D57E85" },
  string: { color: "#A3B367" },
  strong: { bold: true, color: "#DCB16C" },
  subst: { color: "#8b8198" },
  symbol: { color: "#EBB790" },
  tag: { color: "#a59daf" },
  "template-tag": { color: "#BB99B4" },
  "template-variable": { color: "#D57E85" },
  title: { color: "#DCB16C" },
  "title.class": { color: "#DCB16C" },
  "title.class.inherited": { color: "#A3B367" },
  "title.function": { color: "#7297B9" },
  type: { color: "#BB99B4" },
  variable: { color: "#D57E85" },
  "variable.constant": { color: "#EBB790" },
};
