// Generated from highlight.js/styles/base16/bespin.css.

export default {
  addition: { color: "#54be0d" },
  attr: { color: "#cf7d34" },
  attribute: { color: "#5ea6ea" },
  built_in: { color: "#afc4db" },
  bullet: { color: "#cf6a4c" },
  "class title": { color: "#f9ee98" },
  code: { color: "#54be0d" },
  comment: { color: "#666666" },
  default: { background: "#28211c", color: "#8a8986" },
  deletion: { color: "#cf6a4c" },
  doctag: { color: "#afc4db" },
  emphasis: { color: "#9b859d", italic: true },
  "function title": { color: "#5ea6ea" },
  keyword: { color: "#9b859d" },
  "keyword.atrule": { color: "#afc4db" },
  link: { color: "#cf7d34" },
  literal: { color: "#cf7d34" },
  meta: { color: "#937121" },
  "meta keyword": { bold: true, color: "#937121" },
  "meta string": { color: "#937121" },
  "meta-keyword": { bold: true },
  name: { color: "#cf6a4c" },
  number: { color: "#cf7d34" },
  operator: { color: "#8a8986" },
  punctuation: { color: "#8a8986" },
  quote: { color: "#afc4db" },
  regexp: { color: "#afc4db" },
  section: { color: "#5ea6ea" },
  "selector-tag": { color: "#cf6a4c" },
  string: { color: "#54be0d" },
  strong: { bold: true, color: "#f9ee98" },
  subst: { color: "#8a8986" },
  symbol: { color: "#cf7d34" },
  tag: { color: "#797977" },
  "template-tag": { color: "#9b859d" },
  "template-variable": { color: "#cf6a4c" },
  title: { color: "#f9ee98" },
  "title.class": { color: "#f9ee98" },
  "title.class.inherited": { color: "#54be0d" },
  "title.function": { color: "#5ea6ea" },
  type: { color: "#9b859d" },
  variable: { color: "#cf6a4c" },
  "variable.constant": { color: "#cf7d34" },
};
