// Generated from highlight.js/styles/base16/colors.css.

export default {
  addition: { color: "#2ecc40" },
  attr: { color: "#ff851b" },
  attribute: { color: "#0074d9" },
  built_in: { color: "#7fdbff" },
  bullet: { color: "#ff4136" },
  "class title": { color: "#ffdc00" },
  code: { color: "#2ecc40" },
  comment: { color: "#777777" },
  default: { background: "#111111", color: "#bbbbbb" },
  deletion: { color: "#ff4136" },
  doctag: { color: "#7fdbff" },
  emphasis: { color: "#b10dc9", italic: true },
  "function title": { color: "#0074d9" },
  keyword: { color: "#b10dc9" },
  "keyword.atrule": { color: "#7fdbff" },
  link: { color: "#ff851b" },
  literal: { color: "#ff851b" },
  meta: { color: "#85144b" },
  "meta keyword": { bold: true, color: "#85144b" },
  "meta string": { color: "#85144b" },
  "meta-keyword": { bold: true },
  name: { color: "#ff4136" },
  number: { color: "#ff851b" },
  operator: { color: "#bbbbbb" },
  punctuation: { color: "#bbbbbb" },
  quote: { color: "#7fdbff" },
  regexp: { color: "#7fdbff" },
  section: { color: "#0074d9" },
  "selector-tag": { color: "#ff4136" },
  string: { color: "#2ecc40" },
  strong: { bold: true, color: "#ffdc00" },
  subst: { color: "#bbbbbb" },
  symbol: { color: "#ff851b" },
  tag: { color: "#999999" },
  "template-tag": { color: "#b10dc9" },
  "template-variable": { color: "#ff4136" },
  title: { color: "#ffdc00" },
  "title.class": { color: "#ffdc00" },
  "title.class.inherited": { color: "#2ecc40" },
  "title.function": { color: "#0074d9" },
  type: { color: "#b10dc9" },
  variable: { color: "#ff4136" },
  "variable.constant": { color: "#ff851b" },
};
