// Generated from highlight.js/styles/base16/3024.css.

export default {
  addition: { color: "#01a252" },
  attr: { color: "#e8bbd0" },
  attribute: { color: "#01a0e4" },
  built_in: { color: "#b5e4f4" },
  bullet: { color: "#db2d20" },
  "class title": { color: "#fded02" },
  code: { color: "#01a252" },
  comment: { color: "#5c5855" },
  default: { background: "#090300", color: "#a5a2a2" },
  deletion: { color: "#db2d20" },
  doctag: { color: "#b5e4f4" },
  emphasis: { color: "#a16a94", italic: true },
  "function title": { color: "#01a0e4" },
  keyword: { color: "#a16a94" },
  "keyword.atrule": { color: "#b5e4f4" },
  link: { color: "#e8bbd0" },
  literal: { color: "#e8bbd0" },
  meta: { color: "#cdab53" },
  "meta keyword": { bold: true, color: "#cdab53" },
  "meta string": { color: "#cdab53" },
  "meta-keyword": { bold: true },
  name: { color: "#db2d20" },
  number: { color: "#e8bbd0" },
  operator: { color: "#a5a2a2" },
  punctuation: { color: "#a5a2a2" },
  quote: { color: "#b5e4f4" },
  regexp: { color: "#b5e4f4" },
  section: { color: "#01a0e4" },
  "selector-tag": { color: "#db2d20" },
  string: { color: "#01a252" },
  strong: { bold: true, color: "#fded02" },
  subst: { color: "#a5a2a2" },
  symbol: { color: "#e8bbd0" },
  tag: { color: "#807d7c" },
  "template-tag": { color: "#a16a94" },
  "template-variable": { color: "#db2d20" },
  title: { color: "#fded02" },
  "title.class": { color: "#fded02" },
  "title.class.inherited": { color: "#01a252" },
  "title.function": { color: "#01a0e4" },
  type: { color: "#a16a94" },
  variable: { color: "#db2d20" },
  "variable.constant": { color: "#e8bbd0" },
};
