// Generated from highlight.js/styles/base16/qualia.css.

export default {
  addition: { color: "#80C990" },
  attr: { color: "#A3B8EF" },
  attribute: { color: "#50CACD" },
  built_in: { color: "#C8C874" },
  bullet: { color: "#EFA6A2" },
  "class title": { color: "#E6A3DC" },
  code: { color: "#80C990" },
  comment: { color: "#454545" },
  default: { background: "#101010", color: "#C0C0C0" },
  deletion: { color: "#EFA6A2" },
  doctag: { color: "#C8C874" },
  emphasis: { color: "#E0AF85", italic: true },
  "function title": { color: "#50CACD" },
  keyword: { color: "#E0AF85" },
  "keyword.atrule": { color: "#C8C874" },
  link: { color: "#A3B8EF" },
  literal: { color: "#A3B8EF" },
  meta: { color: "#808080" },
  "meta keyword": { bold: true, color: "#808080" },
  "meta string": { color: "#808080" },
  "meta-keyword": { bold: true },
  name: { color: "#EFA6A2" },
  number: { color: "#A3B8EF" },
  operator: { color: "#C0C0C0" },
  punctuation: { color: "#C0C0C0" },
  quote: { color: "#C8C874" },
  regexp: { color: "#C8C874" },
  section: { color: "#50CACD" },
  "selector-tag": { color: "#EFA6A2" },
  string: { color: "#80C990" },
  strong: { bold: true, color: "#E6A3DC" },
  subst: { color: "#C0C0C0" },
  symbol: { color: "#A3B8EF" },
  tag: { color: "#808080" },
  "template-tag": { color: "#E0AF85" },
  "template-variable": { color: "#EFA6A2" },
  title: { color: "#E6A3DC" },
  "title.class": { color: "#E6A3DC" },
  "title.class.inherited": { color: "#80C990" },
  "title.function": { color: "#50CACD" },
  type: { color: "#E0AF85" },
  variable: { color: "#EFA6A2" },
  "variable.constant": { color: "#A3B8EF" },
};
