// Generated from highlight.js/styles/base16/atlas.css.

export default {
  addition: { color: "#7fc06e" },
  attr: { color: "#f08e48" },
  attribute: { color: "#5dd7b9" },
  built_in: { color: "#14747e" },
  bullet: { color: "#ff5a67" },
  "class title": { color: "#ffcc1b" },
  code: { color: "#7fc06e" },
  comment: { color: "#6C8B91" },
  default: { background: "#002635", color: "#a1a19a" },
  deletion: { color: "#ff5a67" },
  doctag: { color: "#14747e" },
  emphasis: { color: "#9a70a4", italic: true },
  "function title": { color: "#5dd7b9" },
  keyword: { color: "#9a70a4" },
  "keyword.atrule": { color: "#14747e" },
  link: { color: "#f08e48" },
  literal: { color: "#f08e48" },
  meta: { color: "#c43060" },
  "meta keyword": { bold: true, color: "#c43060" },
  "meta string": { color: "#c43060" },
  "meta-keyword": { bold: true },
  name: { color: "#ff5a67" },
  number: { color: "#f08e48" },
  operator: { color: "#a1a19a" },
  punctuation: { color: "#a1a19a" },
  quote: { color: "#14747e" },
  regexp: { color: "#14747e" },
  section: { color: "#5dd7b9" },
  "selector-tag": { color: "#ff5a67" },
  string: { color: "#7fc06e" },
  strong: { bold: true, color: "#ffcc1b" },
  subst: { color: "#a1a19a" },
  symbol: { color: "#f08e48" },
  tag: { color: "#869696" },
  "template-tag": { color: "#9a70a4" },
  "template-variable": { color: "#ff5a67" },
  title: { color: "#ffcc1b" },
  "title.class": { color: "#ffcc1b" },
  "title.class.inherited": { color: "#7fc06e" },
  "title.function": { color: "#5dd7b9" },
  type: { color: "#9a70a4" },
  variable: { color: "#ff5a67" },
  "variable.constant": { color: "#f08e48" },
};
