// Generated from highlight.js/styles/base16/danqing.css.

export default {
  addition: { color: "#8AB361" },
  attr: { color: "#B38A61" },
  attribute: { color: "#B0A4E3" },
  built_in: { color: "#30DFF3" },
  bullet: { color: "#F9906F" },
  "class title": { color: "#F0C239" },
  code: { color: "#8AB361" },
  comment: { color: "#9da8a3" },
  default: { background: "#2d302f", color: "#e0f0eF" },
  deletion: { color: "#F9906F" },
  doctag: { color: "#30DFF3" },
  emphasis: { color: "#CCA4E3", italic: true },
  "function title": { color: "#B0A4E3" },
  keyword: { color: "#CCA4E3" },
  "keyword.atrule": { color: "#30DFF3" },
  link: { color: "#B38A61" },
  literal: { color: "#B38A61" },
  meta: { color: "#CA6924" },
  "meta keyword": { bold: true, color: "#CA6924" },
  "meta string": { color: "#CA6924" },
  "meta-keyword": { bold: true },
  name: { color: "#F9906F" },
  number: { color: "#B38A61" },
  operator: { color: "#e0f0eF" },
  punctuation: { color: "#e0f0eF" },
  quote: { color: "#30DFF3" },
  regexp: { color: "#30DFF3" },
  section: { color: "#B0A4E3" },
  "selector-tag": { color: "#F9906F" },
  string: { color: "#8AB361" },
  strong: { bold: true, color: "#F0C239" },
  subst: { color: "#e0f0eF" },
  symbol: { color: "#B38A61" },
  tag: { color: "#cad8d2" },
  "template-tag": { color: "#CCA4E3" },
  "template-variable": { color: "#F9906F" },
  title: { color: "#F0C239" },
  "title.class": { color: "#F0C239" },
  "title.class.inherited": { color: "#8AB361" },
  "title.function": { color: "#B0A4E3" },
  type: { color: "#CCA4E3" },
  variable: { color: "#F9906F" },
  "variable.constant": { color: "#B38A61" },
};
