// Generated from highlight.js/styles/base16/paraiso.css.

export default {
  addition: { color: "#48b685" },
  attr: { color: "#f99b15" },
  attribute: { color: "#06b6ef" },
  built_in: { color: "#5bc4bf" },
  bullet: { color: "#ef6155" },
  "class title": { color: "#fec418" },
  code: { color: "#48b685" },
  comment: { color: "#776e71" },
  default: { background: "#2f1e2e", color: "#a39e9b" },
  deletion: { color: "#ef6155" },
  doctag: { color: "#5bc4bf" },
  emphasis: { color: "#815ba4", italic: true },
  "function title": { color: "#06b6ef" },
  keyword: { color: "#815ba4" },
  "keyword.atrule": { color: "#5bc4bf" },
  link: { color: "#f99b15" },
  literal: { color: "#f99b15" },
  meta: { color: "#e96ba8" },
  "meta keyword": { bold: true, color: "#e96ba8" },
  "meta string": { color: "#e96ba8" },
  "meta-keyword": { bold: true },
  name: { color: "#ef6155" },
  number: { color: "#f99b15" },
  operator: { color: "#a39e9b" },
  punctuation: { color: "#a39e9b" },
  quote: { color: "#5bc4bf" },
  regexp: { color: "#5bc4bf" },
  section: { color: "#06b6ef" },
  "selector-tag": { color: "#ef6155" },
  string: { color: "#48b685" },
  strong: { bold: true, color: "#fec418" },
  subst: { color: "#a39e9b" },
  symbol: { color: "#f99b15" },
  tag: { color: "#8d8687" },
  "template-tag": { color: "#815ba4" },
  "template-variable": { color: "#ef6155" },
  title: { color: "#fec418" },
  "title.class": { color: "#fec418" },
  "title.class.inherited": { color: "#48b685" },
  "title.function": { color: "#06b6ef" },
  type: { color: "#815ba4" },
  variable: { color: "#ef6155" },
  "variable.constant": { color: "#f99b15" },
};
