// Generated from highlight.js/styles/base16/kimber.css.

export default {
  addition: { color: "#99C899" },
  attr: { color: "#476C88" },
  attribute: { color: "#537C9C" },
  built_in: { color: "#78B4B4" },
  bullet: { color: "#C88C8C" },
  "class title": { color: "#D8B56D" },
  code: { color: "#99C899" },
  comment: { color: "#644646" },
  default: { background: "#222222", color: "#DEDEE7" },
  deletion: { color: "#C88C8C" },
  doctag: { color: "#78B4B4" },
  emphasis: { color: "#86CACD", italic: true },
  "function title": { color: "#537C9C" },
  keyword: { color: "#86CACD" },
  "keyword.atrule": { color: "#78B4B4" },
  link: { color: "#476C88" },
  literal: { color: "#476C88" },
  meta: { color: "#704F4F" },
  "meta keyword": { bold: true, color: "#704F4F" },
  "meta string": { color: "#704F4F" },
  "meta-keyword": { bold: true },
  name: { color: "#C88C8C" },
  number: { color: "#476C88" },
  operator: { color: "#DEDEE7" },
  punctuation: { color: "#DEDEE7" },
  quote: { color: "#78B4B4" },
  regexp: { color: "#78B4B4" },
  section: { color: "#537C9C" },
  "selector-tag": { color: "#C88C8C" },
  string: { color: "#99C899" },
  strong: { bold: true, color: "#D8B56D" },
  subst: { color: "#DEDEE7" },
  symbol: { color: "#476C88" },
  tag: { color: "#5A5A5A" },
  "template-tag": { color: "#86CACD" },
  "template-variable": { color: "#C88C8C" },
  title: { color: "#D8B56D" },
  "title.class": { color: "#D8B56D" },
  "title.class.inherited": { color: "#99C899" },
  "title.function": { color: "#537C9C" },
  type: { color: "#86CACD" },
  variable: { color: "#C88C8C" },
  "variable.constant": { color: "#476C88" },
};
