// Generated from highlight.js/styles/base16/rebecca.css.

export default {
  addition: { color: "#6dfedf" },
  attr: { color: "#efe4a1" },
  attribute: { color: "#2de0a7" },
  built_in: { color: "#8eaee0" },
  bullet: { color: "#a0a0c5" },
  "class title": { color: "#ae81ff" },
  code: { color: "#6dfedf" },
  comment: { color: "#666699" },
  default: { background: "#292a44", color: "#f1eff8" },
  deletion: { color: "#a0a0c5" },
  doctag: { color: "#8eaee0" },
  emphasis: { color: "#7aa5ff", italic: true },
  "function title": { color: "#2de0a7" },
  keyword: { color: "#7aa5ff" },
  "keyword.atrule": { color: "#8eaee0" },
  link: { color: "#efe4a1" },
  literal: { color: "#efe4a1" },
  meta: { color: "#ff79c6" },
  "meta keyword": { bold: true, color: "#ff79c6" },
  "meta string": { color: "#ff79c6" },
  "meta-keyword": { bold: true },
  name: { color: "#a0a0c5" },
  number: { color: "#efe4a1" },
  operator: { color: "#f1eff8" },
  punctuation: { color: "#f1eff8" },
  quote: { color: "#8eaee0" },
  regexp: { color: "#8eaee0" },
  section: { color: "#2de0a7" },
  "selector-tag": { color: "#a0a0c5" },
  string: { color: "#6dfedf" },
  strong: { bold: true, color: "#ae81ff" },
  subst: { color: "#f1eff8" },
  symbol: { color: "#efe4a1" },
  tag: { color: "#a0a0c5" },
  "template-tag": { color: "#7aa5ff" },
  "template-variable": { color: "#a0a0c5" },
  title: { color: "#ae81ff" },
  "title.class": { color: "#ae81ff" },
  "title.class.inherited": { color: "#6dfedf" },
  "title.function": { color: "#2de0a7" },
  type: { color: "#7aa5ff" },
  variable: { color: "#a0a0c5" },
  "variable.constant": { color: "#efe4a1" },
};
