// Generated from highlight.js/styles/base16/monokai.css.

export default {
  addition: { color: "#a6e22e" },
  attr: { color: "#fd971f" },
  attribute: { color: "#66d9ef" },
  built_in: { color: "#a1efe4" },
  bullet: { color: "#f92672" },
  "class title": { color: "#f4bf75" },
  code: { color: "#a6e22e" },
  comment: { color: "#75715e" },
  default: { background: "#272822", color: "#f8f8f2" },
  deletion: { color: "#f92672" },
  doctag: { color: "#a1efe4" },
  emphasis: { color: "#ae81ff", italic: true },
  "function title": { color: "#66d9ef" },
  keyword: { color: "#ae81ff" },
  "keyword.atrule": { color: "#a1efe4" },
  link: { color: "#fd971f" },
  literal: { color: "#fd971f" },
  meta: { color: "#cc6633" },
  "meta keyword": { bold: true, color: "#cc6633" },
  "meta string": { color: "#cc6633" },
  "meta-keyword": { bold: true },
  name: { color: "#f92672" },
  number: { color: "#fd971f" },
  operator: { color: "#f8f8f2" },
  punctuation: { color: "#f8f8f2" },
  quote: { color: "#a1efe4" },
  regexp: { color: "#a1efe4" },
  section: { color: "#66d9ef" },
  "selector-tag": { color: "#f92672" },
  string: { color: "#a6e22e" },
  strong: { bold: true, color: "#f4bf75" },
  subst: { color: "#f8f8f2" },
  symbol: { color: "#fd971f" },
  tag: { color: "#a59f85" },
  "template-tag": { color: "#ae81ff" },
  "template-variable": { color: "#f92672" },
  title: { color: "#f4bf75" },
  "title.class": { color: "#f4bf75" },
  "title.class.inherited": { color: "#a6e22e" },
  "title.function": { color: "#66d9ef" },
  type: { color: "#ae81ff" },
  variable: { color: "#f92672" },
  "variable.constant": { color: "#fd971f" },
};
