// Generated from highlight.js/styles/base16/materia.css.

export default {
  addition: { color: "#8BD649" },
  attr: { color: "#EA9560" },
  attribute: { color: "#89DDFF" },
  built_in: { color: "#80CBC4" },
  bullet: { color: "#EC5F67" },
  "class title": { color: "#FFCC00" },
  code: { color: "#8BD649" },
  comment: { color: "#707880" },
  default: { background: "#263238", color: "#CDD3DE" },
  deletion: { color: "#EC5F67" },
  doctag: { color: "#80CBC4" },
  emphasis: { color: "#82AAFF", italic: true },
  "function title": { color: "#89DDFF" },
  keyword: { color: "#82AAFF" },
  "keyword.atrule": { color: "#80CBC4" },
  link: { color: "#EA9560" },
  literal: { color: "#EA9560" },
  meta: { color: "#EC5F67" },
  "meta keyword": { bold: true, color: "#EC5F67" },
  "meta string": { color: "#EC5F67" },
  "meta-keyword": { bold: true },
  name: { color: "#EC5F67" },
  number: { color: "#EA9560" },
  operator: { color: "#CDD3DE" },
  punctuation: { color: "#CDD3DE" },
  quote: { color: "#80CBC4" },
  regexp: { color: "#80CBC4" },
  section: { color: "#89DDFF" },
  "selector-tag": { color: "#EC5F67" },
  string: { color: "#8BD649" },
  strong: { bold: true, color: "#FFCC00" },
  subst: { color: "#CDD3DE" },
  symbol: { color: "#EA9560" },
  tag: { color: "#C9CCD3" },
  "template-tag": { color: "#82AAFF" },
  "template-variable": { color: "#EC5F67" },
  title: { color: "#FFCC00" },
  "title.class": { color: "#FFCC00" },
  "title.class.inherited": { color: "#8BD649" },
  "title.function": { color: "#89DDFF" },
  type: { color: "#82AAFF" },
  variable: { color: "#EC5F67" },
  "variable.constant": { color: "#EA9560" },
};
