// Generated from highlight.js/styles/base16/tender.css.

export default {
  addition: { color: "#c9d05c" },
  attr: { color: "#dc9656" },
  attribute: { color: "#b3deef" },
  built_in: { color: "#73cef4" },
  bullet: { color: "#f43753" },
  "class title": { color: "#ffc24b" },
  code: { color: "#c9d05c" },
  comment: { color: "#4c4c4c" },
  default: { background: "#282828", color: "#eeeeee" },
  deletion: { color: "#f43753" },
  doctag: { color: "#73cef4" },
  emphasis: { color: "#d3b987", italic: true },
  "function title": { color: "#b3deef" },
  keyword: { color: "#d3b987" },
  "keyword.atrule": { color: "#73cef4" },
  link: { color: "#dc9656" },
  literal: { color: "#dc9656" },
  meta: { color: "#a16946" },
  "meta keyword": { bold: true, color: "#a16946" },
  "meta string": { color: "#a16946" },
  "meta-keyword": { bold: true },
  name: { color: "#f43753" },
  number: { color: "#dc9656" },
  operator: { color: "#eeeeee" },
  punctuation: { color: "#eeeeee" },
  quote: { color: "#73cef4" },
  regexp: { color: "#73cef4" },
  section: { color: "#b3deef" },
  "selector-tag": { color: "#f43753" },
  string: { color: "#c9d05c" },
  strong: { bold: true, color: "#ffc24b" },
  subst: { color: "#eeeeee" },
  symbol: { color: "#dc9656" },
  tag: { color: "#b8b8b8" },
  "template-tag": { color: "#d3b987" },
  "template-variable": { color: "#f43753" },
  title: { color: "#ffc24b" },
  "title.class": { color: "#ffc24b" },
  "title.class.inherited": { color: "#c9d05c" },
  "title.function": { color: "#b3deef" },
  type: { color: "#d3b987" },
  variable: { color: "#f43753" },
  "variable.constant": { color: "#dc9656" },
};
