// Generated from highlight.js/styles/base16/framer.css.

export default {
  addition: { color: "#32CCDC" },
  attr: { color: "#FC4769" },
  attribute: { color: "#20BCFC" },
  built_in: { color: "#ACDDFD" },
  bullet: { color: "#FD886B" },
  "class title": { color: "#FECB6E" },
  code: { color: "#32CCDC" },
  comment: { color: "#747474" },
  default: { background: "#181818", color: "#D0D0D0" },
  deletion: { color: "#FD886B" },
  doctag: { color: "#ACDDFD" },
  emphasis: { color: "#BA8CFC", italic: true },
  "function title": { color: "#20BCFC" },
  keyword: { color: "#BA8CFC" },
  "keyword.atrule": { color: "#ACDDFD" },
  link: { color: "#FC4769" },
  literal: { color: "#FC4769" },
  meta: { color: "#B15F4A" },
  "meta keyword": { bold: true, color: "#B15F4A" },
  "meta string": { color: "#B15F4A" },
  "meta-keyword": { bold: true },
  name: { color: "#FD886B" },
  number: { color: "#FC4769" },
  operator: { color: "#D0D0D0" },
  punctuation: { color: "#D0D0D0" },
  quote: { color: "#ACDDFD" },
  regexp: { color: "#ACDDFD" },
  section: { color: "#20BCFC" },
  "selector-tag": { color: "#FD886B" },
  string: { color: "#32CCDC" },
  strong: { bold: true, color: "#FECB6E" },
  subst: { color: "#D0D0D0" },
  symbol: { color: "#FC4769" },
  tag: { color: "#B9B9B9" },
  "template-tag": { color: "#BA8CFC" },
  "template-variable": { color: "#FD886B" },
  title: { color: "#FECB6E" },
  "title.class": { color: "#FECB6E" },
  "title.class.inherited": { color: "#32CCDC" },
  "title.function": { color: "#20BCFC" },
  type: { color: "#BA8CFC" },
  variable: { color: "#FD886B" },
  "variable.constant": { color: "#FC4769" },
};
