// Generated from highlight.js/styles/base16/circus.css.

export default {
  addition: { color: "#84b97c" },
  attr: { color: "#4bb1a7" },
  attribute: { color: "#639ee4" },
  built_in: { color: "#4bb1a7" },
  bullet: { color: "#dc657d" },
  "class title": { color: "#c3ba63" },
  code: { color: "#84b97c" },
  comment: { color: "#5f5a60" },
  default: { background: "#191919", color: "#a7a7a7" },
  deletion: { color: "#dc657d" },
  doctag: { color: "#4bb1a7" },
  emphasis: { color: "#b888e2", italic: true },
  "function title": { color: "#639ee4" },
  keyword: { color: "#b888e2" },
  "keyword.atrule": { color: "#4bb1a7" },
  link: { color: "#4bb1a7" },
  literal: { color: "#4bb1a7" },
  meta: { color: "#b888e2" },
  "meta keyword": { bold: true, color: "#b888e2" },
  "meta string": { color: "#b888e2" },
  "meta-keyword": { bold: true },
  name: { color: "#dc657d" },
  number: { color: "#4bb1a7" },
  operator: { color: "#a7a7a7" },
  punctuation: { color: "#a7a7a7" },
  quote: { color: "#4bb1a7" },
  regexp: { color: "#4bb1a7" },
  section: { color: "#639ee4" },
  "selector-tag": { color: "#dc657d" },
  string: { color: "#84b97c" },
  strong: { bold: true, color: "#c3ba63" },
  subst: { color: "#a7a7a7" },
  symbol: { color: "#4bb1a7" },
  tag: { color: "#505050" },
  "template-tag": { color: "#b888e2" },
  "template-variable": { color: "#dc657d" },
  title: { color: "#c3ba63" },
  "title.class": { color: "#c3ba63" },
  "title.class.inherited": { color: "#84b97c" },
  "title.function": { color: "#639ee4" },
  type: { color: "#b888e2" },
  variable: { color: "#dc657d" },
  "variable.constant": { color: "#4bb1a7" },
};
