// Generated from highlight.js/styles/base16/onedark.css.

export default {
  addition: { color: "#98c379" },
  attr: { color: "#d19a66" },
  attribute: { color: "#61afef" },
  built_in: { color: "#56b6c2" },
  bullet: { color: "#e06c75" },
  "class title": { color: "#e5c07b" },
  code: { color: "#98c379" },
  comment: { color: "#545862" },
  default: { background: "#282c34", color: "#abb2bf" },
  deletion: { color: "#e06c75" },
  doctag: { color: "#56b6c2" },
  emphasis: { color: "#c678dd", italic: true },
  "function title": { color: "#61afef" },
  keyword: { color: "#c678dd" },
  "keyword.atrule": { color: "#56b6c2" },
  link: { color: "#d19a66" },
  literal: { color: "#d19a66" },
  meta: { color: "#be5046" },
  "meta keyword": { bold: true, color: "#be5046" },
  "meta string": { color: "#be5046" },
  "meta-keyword": { bold: true },
  name: { color: "#e06c75" },
  number: { color: "#d19a66" },
  operator: { color: "#abb2bf" },
  punctuation: { color: "#abb2bf" },
  quote: { color: "#56b6c2" },
  regexp: { color: "#56b6c2" },
  section: { color: "#61afef" },
  "selector-tag": { color: "#e06c75" },
  string: { color: "#98c379" },
  strong: { bold: true, color: "#e5c07b" },
  subst: { color: "#abb2bf" },
  symbol: { color: "#d19a66" },
  tag: { color: "#565c64" },
  "template-tag": { color: "#c678dd" },
  "template-variable": { color: "#e06c75" },
  title: { color: "#e5c07b" },
  "title.class": { color: "#e5c07b" },
  "title.class.inherited": { color: "#98c379" },
  "title.function": { color: "#61afef" },
  type: { color: "#c678dd" },
  variable: { color: "#e06c75" },
  "variable.constant": { color: "#d19a66" },
};
