// Generated from highlight.js/styles/base16/flat.css.

export default {
  addition: { color: "#2ECC71" },
  attr: { color: "#E67E22" },
  attribute: { color: "#3498DB" },
  built_in: { color: "#1ABC9C" },
  bullet: { color: "#E74C3C" },
  "class title": { color: "#F1C40F" },
  code: { color: "#2ECC71" },
  comment: { color: "#95A5A6" },
  default: { background: "#2C3E50", color: "#e0e0e0" },
  deletion: { color: "#E74C3C" },
  doctag: { color: "#1ABC9C" },
  emphasis: { color: "#9B59B6", italic: true },
  "function title": { color: "#3498DB" },
  keyword: { color: "#9B59B6" },
  "keyword.atrule": { color: "#1ABC9C" },
  link: { color: "#E67E22" },
  literal: { color: "#E67E22" },
  meta: { color: "#be643c" },
  "meta keyword": { bold: true, color: "#be643c" },
  "meta string": { color: "#be643c" },
  "meta-keyword": { bold: true },
  name: { color: "#E74C3C" },
  number: { color: "#E67E22" },
  operator: { color: "#e0e0e0" },
  punctuation: { color: "#e0e0e0" },
  quote: { color: "#1ABC9C" },
  regexp: { color: "#1ABC9C" },
  section: { color: "#3498DB" },
  "selector-tag": { color: "#E74C3C" },
  string: { color: "#2ECC71" },
  strong: { bold: true, color: "#F1C40F" },
  subst: { color: "#e0e0e0" },
  symbol: { color: "#E67E22" },
  tag: { color: "#BDC3C7" },
  "template-tag": { color: "#9B59B6" },
  "template-variable": { color: "#E74C3C" },
  title: { color: "#F1C40F" },
  "title.class": { color: "#F1C40F" },
  "title.class.inherited": { color: "#2ECC71" },
  "title.function": { color: "#3498DB" },
  type: { color: "#9B59B6" },
  variable: { color: "#E74C3C" },
  "variable.constant": { color: "#E67E22" },
};
