// Generated from highlight.js/styles/base16/isotope.css.

export default {
  addition: { color: "#33ff00" },
  attr: { color: "#ff9900" },
  attribute: { color: "#0066ff" },
  built_in: { color: "#00ffff" },
  bullet: { color: "#ff0000" },
  "class title": { color: "#ff0099" },
  code: { color: "#33ff00" },
  comment: { color: "#808080" },
  default: { background: "#000000", color: "#d0d0d0" },
  deletion: { color: "#ff0000" },
  doctag: { color: "#00ffff" },
  emphasis: { color: "#cc00ff", italic: true },
  "function title": { color: "#0066ff" },
  keyword: { color: "#cc00ff" },
  "keyword.atrule": { color: "#00ffff" },
  link: { color: "#ff9900" },
  literal: { color: "#ff9900" },
  meta: { color: "#3300ff" },
  "meta keyword": { bold: true, color: "#3300ff" },
  "meta string": { color: "#3300ff" },
  "meta-keyword": { bold: true },
  name: { color: "#ff0000" },
  number: { color: "#ff9900" },
  operator: { color: "#d0d0d0" },
  punctuation: { color: "#d0d0d0" },
  quote: { color: "#00ffff" },
  regexp: { color: "#00ffff" },
  section: { color: "#0066ff" },
  "selector-tag": { color: "#ff0000" },
  string: { color: "#33ff00" },
  strong: { bold: true, color: "#ff0099" },
  subst: { color: "#d0d0d0" },
  symbol: { color: "#ff9900" },
  tag: { color: "#c0c0c0" },
  "template-tag": { color: "#cc00ff" },
  "template-variable": { color: "#ff0000" },
  title: { color: "#ff0099" },
  "title.class": { color: "#ff0099" },
  "title.class.inherited": { color: "#33ff00" },
  "title.function": { color: "#0066ff" },
  type: { color: "#cc00ff" },
  variable: { color: "#ff0000" },
  "variable.constant": { color: "#ff9900" },
};
