// Generated from highlight.js/styles/base16/zenburn.css.

export default {
  addition: { color: "#5f7f5f" },
  attr: { color: "#dfaf8f" },
  attribute: { color: "#7cb8bb" },
  built_in: { color: "#93e0e3" },
  bullet: { color: "#dca3a3" },
  "class title": { color: "#e0cf9f" },
  code: { color: "#5f7f5f" },
  comment: { color: "#6f6f6f" },
  default: { background: "#383838", color: "#dcdccc" },
  deletion: { color: "#dca3a3" },
  doctag: { color: "#93e0e3" },
  emphasis: { color: "#dc8cc3", italic: true },
  "function title": { color: "#7cb8bb" },
  keyword: { color: "#dc8cc3" },
  "keyword.atrule": { color: "#93e0e3" },
  link: { color: "#dfaf8f" },
  literal: { color: "#dfaf8f" },
  meta: { color: "#000000" },
  "meta keyword": { bold: true, color: "#000000" },
  "meta string": { color: "#000000" },
  "meta-keyword": { bold: true },
  name: { color: "#dca3a3" },
  number: { color: "#dfaf8f" },
  operator: { color: "#dcdccc" },
  punctuation: { color: "#dcdccc" },
  quote: { color: "#93e0e3" },
  regexp: { color: "#93e0e3" },
  section: { color: "#7cb8bb" },
  "selector-tag": { color: "#dca3a3" },
  string: { color: "#5f7f5f" },
  strong: { bold: true, color: "#e0cf9f" },
  subst: { color: "#dcdccc" },
  symbol: { color: "#dfaf8f" },
  tag: { color: "#808080" },
  "template-tag": { color: "#dc8cc3" },
  "template-variable": { color: "#dca3a3" },
  title: { color: "#e0cf9f" },
  "title.class": { color: "#e0cf9f" },
  "title.class.inherited": { color: "#5f7f5f" },
  "title.function": { color: "#7cb8bb" },
  type: { color: "#dc8cc3" },
  variable: { color: "#dca3a3" },
  "variable.constant": { color: "#dfaf8f" },
};
