// Generated from highlight.js/styles/codepen-embed.css.

export default {
  addition: { color: "#8f9c6c" },
  attribute: { color: "#9b869b" },
  built_in: { color: "#ab875d" },
  bullet: { color: "#ab875d" },
  comment: { color: "#777" },
  default: { background: "#222", color: "#fff" },
  deletion: { color: "#ab875d" },
  emphasis: { italic: true },
  keyword: { color: "#8f9c6c" },
  link: { color: "#ab875d" },
  literal: { color: "#ab875d" },
  meta: { color: "#ab875d" },
  name: { color: "#9b869b" },
  number: { color: "#ab875d" },
  params: { color: "#ab875d" },
  quote: { color: "#777" },
  regexp: { color: "#ab875d" },
  section: { color: "#9b869b" },
  "selector-class": { color: "#9b869b" },
  "selector-id": { color: "#9b869b" },
  "selector-tag": { color: "#8f9c6c" },
  string: { color: "#8f9c6c" },
  strong: { bold: true },
  symbol: { color: "#ab875d" },
  tag: { color: "#ab875d" },
  "template-variable": { color: "#ab875d" },
  title: { color: "#9b869b" },
  type: { color: "#9b869b" },
  variable: { color: "#ab875d" },
};
