// Generated from highlight.js/styles/cybertopia-dimmer.css.

export default {
  addition: { color: "#02c797" },
  attr: { color: "#BE6446" },
  attribute: { color: "#02c797" },
  built_in: { color: "#c5bb02" },
  bullet: { color: "#469EBE" },
  "char.escape": { color: "#469EBE" },
  "class title": { color: "#c5bb02" },
  code: { color: "#5c6370", italic: true },
  comment: { color: "#5c6370", italic: true },
  default: { background: "#101010", color: "#abb2bf" },
  deletion: { color: "#C50233" },
  doctag: { color: "#A246BE" },
  emphasis: { italic: true },
  formula: { color: "#A246BE" },
  keyword: { color: "#A246BE" },
  link: { color: "#469EBE", underline: true },
  literal: { color: "#97C502" },
  meta: { color: "#469EBE" },
  "meta keyword": { color: "#A246BE" },
  "meta string": { color: "#02c797" },
  name: { color: "#C50233" },
  number: { color: "#BE6446" },
  operator: { color: "#64BE46" },
  params: { color: "#64BE46" },
  property: { color: "#469EBE" },
  punctuation: { color: "#BE6446" },
  quote: { color: "#5c6370", italic: true },
  regexp: { color: "#02c797" },
  section: { color: "#C50233" },
  "selector-attr": { color: "#BE6446" },
  "selector-class": { color: "#BE6446" },
  "selector-id": { color: "#469EBE" },
  "selector-pseudo": { color: "#BE6446" },
  "selector-tag": { color: "#C50233" },
  string: { color: "#02c797" },
  strong: { bold: true },
  subst: { color: "#C50233" },
  symbol: { color: "#469EBE" },
  tag: { color: "#469EBE" },
  "template-tag": { color: "#64BE46" },
  "template-variable": { color: "#BE6446" },
  title: { color: "#469EBE" },
  "title.class": { color: "#c5bb02" },
  "title.class.inherited": { color: "#c5bb02" },
  "title.function": { color: "#469EBE" },
  type: { color: "#BE6446" },
  variable: { color: "#BE6446" },
  "variable.language": { color: "#BE6446" },
};
