// Generated from highlight.js/styles/dark.css.

export default {
  addition: { color: "#d88" },
  attribute: { color: "#d88" },
  built_in: { color: "#d88" },
  bullet: { color: "#d88" },
  comment: { color: "#979797" },
  default: { background: "#303030", color: "#ddd" },
  deletion: { color: "#979797" },
  doctag: { bold: true },
  emphasis: { italic: true },
  keyword: { bold: true, color: "#ffffff" },
  link: { color: "#ffffff" },
  literal: { bold: true, color: "#ffffff" },
  meta: { color: "#979797" },
  name: { bold: true, color: "#d88" },
  quote: { color: "#979797" },
  section: { bold: true, color: "#ffffff" },
  "selector-tag": { bold: true, color: "#ffffff" },
  string: { color: "#d88" },
  strong: { bold: true },
  symbol: { color: "#d88" },
  "template-tag": { color: "#d88" },
  "template-variable": { color: "#d88" },
  title: { bold: true, color: "#d88" },
  type: { bold: true, color: "#d88" },
  variable: { color: "#d88" },
};
