// Generated from highlight.js/styles/far.css.

export default {
  addition: { color: "#ff0" },
  attribute: { color: "#ff0" },
  built_in: { color: "#ff0" },
  bullet: { color: "#ff0" },
  comment: { color: "#888" },
  default: { background: "#000080", color: "#0ff" },
  deletion: { color: "#888" },
  doctag: { color: "#888" },
  emphasis: { italic: true },
  keyword: { bold: true, color: "#fff" },
  link: { color: "#0f0" },
  literal: { color: "#0f0" },
  meta: { color: "#008080" },
  name: { bold: true, color: "#fff" },
  number: { color: "#0f0" },
  quote: { color: "#888" },
  regexp: { color: "#0f0" },
  section: { bold: true, color: "#fff" },
  "selector-class": { color: "#fff" },
  "selector-id": { color: "#fff" },
  "selector-tag": { bold: true, color: "#fff" },
  string: { color: "#ff0" },
  strong: { bold: true },
  symbol: { color: "#ff0" },
  "template-tag": { color: "#ff0" },
  "template-variable": { color: "#ff0" },
  title: { bold: true },
  type: { color: "#fff" },
  variable: { color: "#fff" },
};
