// Generated from highlight.js/styles/felipec.css.

export default {
  addition: { color: "#93e4a4" },
  attr: { color: "#d991d2" },
  attribute: { color: "#d991d2" },
  built_in: { color: "#5fb8f2" },
  bullet: { color: "#90aafa" },
  class: { color: "#65e7d1" },
  code: { color: "#9e9da4" },
  comment: { color: "#9e9da4" },
  default: { background: "#1d1c21", color: "#dedde4" },
  deletion: { color: "#f09080" },
  doctag: { color: "#ffbb7b" },
  emphasis: { italic: true },
  keyword: { color: "#5fb8f2" },
  link: { color: "#ec8dab" },
  literal: { bold: true, color: "#f09080" },
  meta: { color: "#ffbb7b" },
  name: { color: "#30c2d8" },
  number: { color: "#f09080" },
  operator: { color: "#ffbb7b" },
  params: { color: "#d991d2" },
  property: { color: "#65e7d1" },
  punctuation: { color: "#ffbb7b" },
  quote: { color: "#9e9da4" },
  regexp: { color: "#93e4a4" },
  section: { color: "#90aafa" },
  "selector-attr": { color: "#ffbb7b" },
  "selector-class": { color: "#c4da7d" },
  "selector-id": { color: "#c4da7d" },
  "selector-pseudo": { color: "#ba9cef" },
  "selector-tag": { color: "#30c2d8" },
  string: { color: "#93e4a4" },
  strong: { bold: true },
  subst: { color: "#ffbb7b" },
  symbol: { color: "#ec8dab" },
  tag: { color: "#c4da7d" },
  "template-variable": { color: "#ffbb7b" },
  title: { bold: true, color: "#c4da7d" },
  type: { color: "#fddb7c" },
  variable: { color: "#d991d2" },
};
