// Generated from highlight.js/styles/github-dark.css.

export default {
  addition: { background: "#033a16", color: "#aff5b4" },
  attr: { color: "#79c0ff" },
  attribute: { color: "#79c0ff" },
  built_in: { color: "#ffa657" },
  bullet: { color: "#f2cc60" },
  code: { color: "#8b949e" },
  comment: { color: "#8b949e" },
  default: { background: "#0d1117", color: "#c9d1d9" },
  deletion: { background: "#67060c", color: "#ffdcd7" },
  doctag: { color: "#ff7b72" },
  emphasis: { color: "#c9d1d9", italic: true },
  formula: { color: "#8b949e" },
  keyword: { color: "#ff7b72" },
  literal: { color: "#79c0ff" },
  meta: { color: "#79c0ff" },
  "meta keyword": { color: "#ff7b72" },
  "meta string": { color: "#a5d6ff" },
  name: { color: "#7ee787" },
  number: { color: "#79c0ff" },
  operator: { color: "#79c0ff" },
  quote: { color: "#7ee787" },
  regexp: { color: "#a5d6ff" },
  section: { bold: true, color: "#1f6feb" },
  "selector-attr": { color: "#79c0ff" },
  "selector-class": { color: "#79c0ff" },
  "selector-id": { color: "#79c0ff" },
  "selector-pseudo": { color: "#7ee787" },
  "selector-tag": { color: "#7ee787" },
  string: { color: "#a5d6ff" },
  strong: { bold: true, color: "#c9d1d9" },
  subst: { color: "#c9d1d9" },
  symbol: { color: "#ffa657" },
  "template-tag": { color: "#ff7b72" },
  "template-variable": { color: "#ff7b72" },
  title: { color: "#d2a8ff" },
  "title.class": { color: "#d2a8ff" },
  "title.class.inherited": { color: "#d2a8ff" },
  "title.function": { color: "#d2a8ff" },
  type: { color: "#ff7b72" },
  variable: { color: "#79c0ff" },
  "variable.language": { color: "#ff7b72" },
};
