// Generated from highlight.js/styles/gml.css.

export default {
  addition: { color: "#C0C0C0" },
  attribute: { color: "#C0C0C0" },
  built_in: { color: "#FFB871" },
  bullet: { color: "#C0C0C0" },
  code: { color: "#C0C0C0" },
  comment: { color: "#5B995B" },
  default: { background: "#222222", color: "#C0C0C0" },
  deletion: { color: "#C0C0C0" },
  doctag: { color: "#C0C0C0" },
  emphasis: { italic: true },
  function: { color: "#C0C0C0" },
  keyword: { bold: true, color: "#FFB871" },
  link: { color: "#C0C0C0" },
  literal: { color: "#FF8080" },
  meta: { color: "#C0C0C0" },
  "meta keyword": { color: "#C0C0C0" },
  name: { color: "#C0C0C0" },
  number: { color: "#FF8080" },
  quote: { color: "#C0C0C0" },
  regexp: { color: "#C0C0C0" },
  section: { color: "#C0C0C0" },
  "selector-attr": { color: "#C0C0C0" },
  "selector-class": { color: "#C0C0C0" },
  "selector-id": { color: "#C0C0C0" },
  "selector-pseudo": { color: "#C0C0C0" },
  "selector-tag": { color: "#C0C0C0" },
  string: { color: "#FFFF00" },
  strong: { bold: true },
  subst: { color: "#C0C0C0" },
  symbol: { color: "#58E55A" },
  "template-tag": { color: "#C0C0C0" },
  "template-variable": { color: "#C0C0C0" },
  title: { color: "#C0C0C0" },
  type: { color: "#C0C0C0" },
  variable: { color: "#C0C0C0" },
};
