// Generated from highlight.js/styles/googlecode.css.

export default {
  addition: { background: "#baeeba" },
  attr: { color: "#606" },
  attribute: { color: "#000" },
  built_in: { color: "#606" },
  bullet: { color: "#066" },
  comment: { color: "#800" },
  default: { background: "#ffffff", color: "#000000" },
  deletion: { background: "#ffc8bd" },
  doctag: { bold: true, color: "#606" },
  emphasis: { italic: true },
  formula: { background: "#eee", italic: true },
  keyword: { color: "#008" },
  link: { color: "#066" },
  literal: { color: "#066" },
  meta: { color: "#066" },
  name: { color: "#008" },
  number: { color: "#066" },
  params: { color: "#606" },
  quote: { color: "#800" },
  regexp: { color: "#080" },
  section: { color: "#008" },
  "selector-attr": { color: "#080" },
  "selector-class": { color: "#9B703F" },
  "selector-id": { color: "#9B703F" },
  "selector-pseudo": { color: "#080" },
  "selector-tag": { color: "#008" },
  string: { color: "#080" },
  strong: { bold: true },
  subst: { color: "#000" },
  symbol: { color: "#066" },
  "template-variable": { color: "#660" },
  title: { color: "#606" },
  type: { color: "#606" },
  variable: { color: "#660" },
};
