// Generated from highlight.js/styles/gradient-dark.css.

export default {
  addition: { color: "#E7FF9F" },
  attr: { color: "#AEFBFF" },
  attribute: { color: "#E7FF9F" },
  built_in: { color: "#FFC800" },
  bullet: { color: "#F19FFF" },
  class: { color: "#FFC800" },
  comment: { color: "#af8dd9" },
  default: { background: "#652487", color: "#e7e4eb" },
  deletion: { color: "#FF9E44" },
  doctag: { color: "#af8dd9" },
  emphasis: { italic: true },
  formula: { color: "#FFC800" },
  function: { color: "#FFC800" },
  keyword: { bold: true, color: "#17fc95" },
  link: { color: "#C5FE00" },
  literal: { color: "#FF9E44" },
  meta: { color: "#af8dd9" },
  "meta keyword": { color: "#17fc95" },
  name: { color: "#FFC800" },
  number: { color: "#C5FE00" },
  params: { bold: true, color: "#F19FFF" },
  quote: { color: "#af8dd9", italic: true },
  regexp: { color: "#AEFBFF" },
  section: { bold: true, color: "#17fc95" },
  "selector-class": { bold: true, color: "#F19FFF" },
  "selector-id": { bold: true, color: "#AEFBFF" },
  "selector-pseudo": { color: "#FF9E44" },
  "selector-tag": { bold: true, color: "#AEFBFF" },
  string: { color: "#38c0ff" },
  strong: { bold: true },
  subtr: { color: "#e7e4eb" },
  symbol: { color: "#17fc95" },
  tag: { color: "#AEFBFF" },
  "template-tag": { bold: true, color: "#AEFBFF" },
  "template-variable": { color: "#E447FF" },
  title: { color: "#FFC800" },
  type: { color: "#17fc95" },
  variable: { color: "#E447FF" },
};
