// Generated from highlight.js/styles/grayscale.css.

export default {
  addition: { color: "#000" },
  built_in: { color: "#000", underline: true },
  bullet: { color: "#000" },
  "class title": { bold: true, color: "#333" },
  comment: { color: "#777", italic: true },
  default: { background: "#fff", color: "#333" },
  deletion: { color: "#fff" },
  doctag: { color: "#333" },
  emphasis: { italic: true },
  formula: { color: "#333" },
  keyword: { bold: true, color: "#333" },
  link: { color: "#000" },
  literal: { color: "#777" },
  meta: { bold: true, color: "#999" },
  name: { bold: true, color: "#333" },
  number: { color: "#777" },
  quote: { color: "#777", italic: true },
  regexp: { color: "#333" },
  section: { bold: true, color: "#000" },
  "selector-id": { bold: true, color: "#000" },
  "selector-tag": { bold: true, color: "#333" },
  string: { color: "#333" },
  strong: { bold: true },
  subst: { bold: true, color: "#333" },
  symbol: { color: "#000" },
  tag: { color: "#333" },
  title: { bold: true, color: "#000" },
  "title.class": { bold: true, color: "#333" },
  type: { bold: true, color: "#333" },
};
