// Generated from highlight.js/styles/hybrid.css.

export default {
  addition: { color: "#b5bd68" },
  attribute: { color: "#b294bb" },
  built_in: { color: "#de935f" },
  bullet: { color: "#81a2be" },
  code: { color: "#b294bb" },
  comment: { color: "#707880" },
  default: { background: "#1d1f21", color: "#c5c8c6" },
  deletion: { color: "#cc6666" },
  doctag: { color: "#b5bd68" },
  emphasis: { italic: true },
  keyword: { color: "#81a2be" },
  link: { color: "#cc6666" },
  literal: { color: "#cc6666" },
  meta: { color: "#707880" },
  "meta keyword": { color: "#707880" },
  name: { color: "#f0c674" },
  number: { color: "#cc6666" },
  quote: { color: "#de935f" },
  regexp: { color: "#b5bd68" },
  section: { color: "#de935f" },
  "selector-attr": { color: "#b5bd68" },
  "selector-class": { color: "#de935f" },
  "selector-id": { color: "#b294bb" },
  "selector-pseudo": { color: "#b5bd68" },
  "selector-tag": { color: "#81a2be" },
  string: { color: "#b5bd68" },
  strong: { bold: true },
  subst: { color: "#8abeb7" },
  symbol: { color: "#cc6666" },
  tag: { color: "#81a2be" },
  "template-tag": { color: "#8abeb7" },
  "template-variable": { color: "#8abeb7" },
  title: { color: "#f0c674" },
  type: { color: "#de935f" },
  variable: { color: "#8abeb7" },
};
