// Generated from highlight.js/styles/idea.css.

export default {
  addition: { background: "#baeeba" },
  attribute: { bold: true, color: "#0000ff" },
  bullet: { background: "#d0eded", color: "#000", italic: true },
  comment: { color: "#808080", italic: true },
  default: { background: "#fff", color: "#000" },
  deletion: { background: "#ffc8bd" },
  doctag: { underline: true },
  emphasis: { italic: true },
  formula: { background: "#d0eded", color: "#000", italic: true },
  keyword: { bold: true, color: "#000080" },
  link: { bold: true, color: "#0000ff" },
  literal: { bold: true, color: "#000080" },
  meta: { color: "#808000" },
  name: { bold: true, color: "#000080" },
  number: { bold: true, color: "#0000ff" },
  quote: { color: "#808080", italic: true },
  regexp: { bold: true, color: "#0000ff" },
  section: { bold: true, color: "#000080" },
  "selector-class": { bold: true, color: "#000080" },
  "selector-id": { bold: true, color: "#000080" },
  "selector-tag": { bold: true, color: "#000080" },
  string: { bold: true, color: "#008000" },
  strong: { bold: true },
  subst: { color: "#000" },
  symbol: { background: "#d0eded", color: "#000", italic: true },
  tag: { background: "#efefef" },
  "template-variable": { color: "#660e7a" },
  title: { color: "#000" },
  type: { bold: true, color: "#000080" },
  variable: { color: "#660e7a" },
};
