// Generated from highlight.js/styles/ir-black.css.

export default {
  addition: { color: "#a8ff60" },
  attribute: { color: "#ffffb6" },
  bullet: { color: "#c6c5fe" },
  comment: { color: "#7c7c7c" },
  default: { background: "#000", color: "#f8f8f8" },
  deletion: { color: "#ff73fd" },
  doctag: { color: "#ffffb6" },
  emphasis: { italic: true },
  keyword: { color: "#96cbfe" },
  link: { color: "#e9c062" },
  literal: { color: "#c6c5fe" },
  meta: { color: "#7c7c7c" },
  name: { color: "#96cbfe" },
  number: { color: "#ff73fd" },
  quote: { color: "#7c7c7c" },
  regexp: { color: "#e9c062" },
  section: { color: "#ffffb6" },
  "selector-attr": { color: "#a8ff60" },
  "selector-id": { color: "#ffffb6" },
  "selector-pseudo": { color: "#a8ff60" },
  "selector-tag": { color: "#96cbfe" },
  string: { color: "#a8ff60" },
  strong: { bold: true },
  subst: { color: "#daefa3" },
  symbol: { color: "#c6c5fe" },
  tag: { color: "#96cbfe" },
  "template-variable": { color: "#c6c5fe" },
  title: { color: "#ffffb6" },
  type: { color: "#ffffb6" },
  variable: { color: "#c6c5fe" },
};
