// Generated from highlight.js/styles/lightfair.css.

export default {
  addition: { color: "#25c6c6" },
  attribute: { bold: true },
  built_in: { color: "#25c6c6" },
  bullet: { color: "#25c6c6" },
  code: { color: "#25c6c6" },
  comment: { color: "#888888" },
  default: { background: "#fff", color: "#444" },
  deletion: { color: "#4286f4" },
  doctag: { bold: true },
  emphasis: { italic: true },
  keyword: { bold: true },
  link: { color: "#BC6060" },
  literal: { color: "#62bcbc" },
  meta: { color: "#778899" },
  "meta keyword": { bold: true },
  "meta string": { color: "#4d99bf" },
  name: { bold: true, color: "#01a3a3" },
  number: { color: "#4286f4" },
  quote: { color: "#4286f4" },
  regexp: { color: "#BC6060" },
  section: { bold: true, color: "#4286f4" },
  "selector-attr": { color: "#BC6060" },
  "selector-class": { color: "#4286f4" },
  "selector-id": { color: "#4286f4" },
  "selector-pseudo": { color: "#BC6060" },
  "selector-tag": { bold: true },
  string: { color: "#4286f4" },
  strong: { bold: true },
  symbol: { color: "#BC6060" },
  tag: { color: "#778899" },
  "template-tag": { color: "#4286f4" },
  "template-variable": { color: "#BC6060" },
  title: { bold: true, color: "#4286f4" },
  type: { color: "#4286f4" },
  variable: { color: "#BC6060" },
};
