// Generated from highlight.js/styles/lioshi.css.

export default {
  addition: { color: "#b5bd68" },
  attribute: { color: "#f0c674" },
  built_in: { color: "#de935f" },
  bullet: { color: "#b5bd68" },
  class: { color: "#be94bb" },
  comment: { color: "#8d8d8d" },
  default: { background: "#303030", color: "#c5c8c6" },
  deletion: { color: "#cc6666" },
  emphasis: { italic: true },
  function: { color: "#be94bb" },
  keyword: { color: "#be94bb" },
  literal: { color: "#de935f" },
  meta: { color: "#81a2be" },
  name: { color: "#cc6666" },
  number: { color: "#de935f" },
  params: { color: "#b5bd68" },
  quote: { color: "#b3c7d8" },
  regexp: { color: "#cc6666" },
  section: { color: "#81a2be" },
  "selector-class": { color: "#cc6666" },
  "selector-id": { color: "#cc6666" },
  "selector-tag": { color: "#be94bb" },
  string: { color: "#b5bd68" },
  strong: { bold: true },
  "subst link": { color: "#de935f" },
  symbol: { color: "#dbc4d9" },
  tag: { color: "#cc6666" },
  "template-variable": { color: "#cc6666" },
  title: { color: "#81a2be" },
  type: { color: "#de935f" },
  variable: { color: "#cc6666" },
};
