// Generated from highlight.js/styles/mono-blue.css.

export default {
  addition: { color: "#0048ab" },
  attribute: { color: "#4c81c9" },
  built_in: { color: "#0048ab" },
  bullet: { color: "#4c81c9" },
  comment: { color: "#738191" },
  default: { background: "#eaeef3", color: "#00193a" },
  deletion: { color: "#4c81c9" },
  doctag: { bold: true },
  emphasis: { italic: true },
  keyword: { bold: true },
  link: { color: "#4c81c9" },
  literal: { color: "#0048ab" },
  meta: { color: "#4c81c9" },
  name: { bold: true, color: "#0048ab" },
  quote: { color: "#0048ab" },
  regexp: { color: "#4c81c9" },
  section: { bold: true, color: "#0048ab" },
  "selector-class": { color: "#0048ab" },
  "selector-id": { color: "#0048ab" },
  "selector-tag": { bold: true },
  string: { color: "#0048ab" },
  strong: { bold: true },
  subst: { color: "#4c81c9" },
  symbol: { color: "#4c81c9" },
  tag: { color: "#0048ab" },
  "template-variable": { color: "#4c81c9" },
  title: { bold: true, color: "#0048ab" },
  type: { color: "#0048ab" },
  variable: { color: "#4c81c9" },
};
