// Generated from highlight.js/styles/monokai-sublime.css.

export default {
  addition: { color: "#e6db74" },
  attr: { color: "#f92672" },
  attribute: { color: "#66d9ef" },
  built_in: { color: "#e6db74" },
  bullet: { color: "#ae81ff" },
  "class title": { color: "#f8f8f2" },
  code: { color: "#a6e22e" },
  comment: { color: "#75715e" },
  default: { background: "#23241f", color: "#f8f8f2" },
  deletion: { color: "#75715e" },
  emphasis: { color: "#a8a8a2", italic: true },
  keyword: { color: "#f92672" },
  link: { color: "#ae81ff" },
  literal: { color: "#ae81ff" },
  meta: { color: "#75715e" },
  name: { color: "#f92672" },
  number: { color: "#ae81ff" },
  params: { color: "#f8f8f2" },
  quote: { color: "#ae81ff" },
  regexp: { color: "#ae81ff" },
  section: { color: "#a6e22e" },
  "selector-attr": { color: "#e6db74" },
  "selector-class": { color: "#a6e22e" },
  "selector-id": { color: "#e6db74" },
  "selector-pseudo": { color: "#e6db74" },
  "selector-tag": { color: "#f92672" },
  string: { color: "#e6db74" },
  strong: { bold: true, color: "#a8a8a2" },
  subst: { color: "#f8f8f2" },
  symbol: { color: "#66d9ef" },
  tag: { color: "#f8f8f2" },
  "template-variable": { color: "#e6db74" },
  title: { color: "#a6e22e" },
  "title.class": { color: "#f8f8f2" },
  type: { color: "#e6db74" },
  variable: { color: "#e6db74" },
};
