// Generated from highlight.js/styles/monokai.css.

export default {
  addition: { color: "#a6e22e" },
  attr: { color: "#bf79db" },
  attribute: { color: "#bf79db" },
  built_in: { color: "#a6e22e" },
  bullet: { color: "#a6e22e" },
  "class title": { color: "#ffffff" },
  code: { color: "#66d9ef" },
  comment: { color: "#75715e" },
  default: { background: "#272822", color: "#ddd" },
  deletion: { color: "#75715e" },
  doctag: { bold: true },
  emphasis: { color: "#a6e22e" },
  keyword: { bold: true, color: "#f92672" },
  link: { color: "#bf79db" },
  literal: { bold: true, color: "#f92672" },
  meta: { color: "#75715e" },
  name: { color: "#f92672" },
  number: { color: "#f92672" },
  quote: { color: "#75715e" },
  regexp: { color: "#bf79db" },
  section: { bold: true, color: "#a6e22e" },
  "selector-attr": { color: "#a6e22e" },
  "selector-id": { bold: true },
  "selector-pseudo": { color: "#a6e22e" },
  "selector-tag": { bold: true, color: "#f92672" },
  string: { color: "#a6e22e" },
  strong: { color: "#f92672" },
  subst: { color: "#a6e22e" },
  symbol: { color: "#bf79db" },
  tag: { color: "#f92672" },
  "template-tag": { color: "#a6e22e" },
  "template-variable": { color: "#a6e22e" },
  title: { bold: true, color: "#a6e22e" },
  "title.class": { color: "#ffffff" },
  type: { bold: true, color: "#a6e22e" },
  variable: { color: "#a6e22e" },
};
