// Generated from highlight.js/styles/night-owl.css.

export default {
  addition: { italic: true },
  attr: { color: "#7fdbca" },
  attribute: { color: "#80cbc4" },
  built_in: { color: "#addb67", italic: true },
  bullet: { color: "#d9f5dd" },
  class: { color: "#ffcb8b" },
  code: { color: "#80CBC4" },
  comment: { color: "#637777", italic: true },
  default: { background: "#011627", color: "#d6deeb" },
  deletion: { italic: true },
  doctag: { color: "#7fdbca" },
  emphasis: { color: "#c792ea", italic: true },
  formula: { color: "#c792ea" },
  function: { color: "#82AAFF" },
  keyword: { color: "#c792ea", italic: true },
  link: { color: "#ff869a" },
  literal: { color: "#ff5874" },
  meta: { color: "#82aaff" },
  "meta keyword": { color: "#82aaff" },
  "meta string": { color: "#ecc48d" },
  name: { color: "#7fdbca" },
  number: { color: "#F78C6C" },
  params: { color: "#7fdbca" },
  quote: { color: "#697098", italic: true },
  regexp: { color: "#5ca7e4" },
  section: { color: "#82b1ff" },
  "selector-attr": { color: "#c792ea", italic: true },
  "selector-class": { color: "#addb67", italic: true },
  "selector-id": { color: "#fad430" },
  "selector-pseudo": { color: "#c792ea", italic: true },
  "selector-tag": { color: "#ff6363" },
  string: { color: "#ecc48d" },
  strong: { bold: true, color: "#addb67" },
  subst: { color: "#d3423e" },
  symbol: { color: "#82aaff" },
  tag: { color: "#7fdbca" },
  "template-tag": { color: "#c792ea" },
  "template-variable": { color: "#addb67" },
  title: { color: "#DCDCAA", italic: true },
  type: { color: "#82aaff" },
  variable: { color: "#addb67" },
};
