// Generated from highlight.js/styles/nnfx-light.css.

export default {
  addition: { background: "#beb" },
  attr: { bold: true, color: "#000" },
  built_in: { color: "#808" },
  bullet: { color: "#f40" },
  "class title": { bold: true, color: "#639" },
  code: { color: "#00f" },
  comment: { color: "#070", italic: true },
  default: { background: "#fff", color: "#000" },
  deletion: { background: "#fbb" },
  doctag: { bold: true },
  emphasis: { italic: true },
  formula: { background: "#eee", italic: true },
  "function title": { color: "#000" },
  keyword: { color: "#808" },
  link: { color: "#00f" },
  meta: { color: "#269" },
  "meta string": { color: "#00f" },
  name: { bold: true, color: "#808" },
  number: { color: "#00f" },
  quote: { color: "#070", italic: true },
  regexp: { color: "#00f" },
  section: { bold: true, color: "#48b" },
  "selector-class": { bold: true, color: "#48b" },
  "selector-id": { bold: true, color: "#48b" },
  "selector-pseudo": { bold: true, color: "#48b", italic: true },
  "selector-tag": { bold: true, color: "#48b" },
  string: { color: "#00f" },
  strong: { bold: true },
  subst: { color: "#000" },
  symbol: { color: "#f40" },
  tag: { color: "#000" },
  "template-variable": { color: "#f40" },
  title: { color: "#f40" },
  "title.class": { bold: true, color: "#639" },
  "title.function": { color: "#000" },
  type: { bold: true, color: "#639" },
  variable: { color: "#f40" },
};
