// Generated from highlight.js/styles/nnfx-dark.css.

export default {
  addition: { background: "#797" },
  attr: { bold: true, color: "#fff" },
  built_in: { color: "#a7a" },
  bullet: { color: "#d40" },
  "class title": { bold: true, color: "#96c" },
  code: { color: "#bce" },
  comment: { color: "#9c6", italic: true },
  default: { background: "#333", color: "#fff" },
  deletion: { background: "#c99" },
  doctag: { bold: true },
  emphasis: { italic: true },
  formula: { background: "#eee", italic: true },
  "function title": { color: "#fff" },
  keyword: { color: "#a7a" },
  link: { color: "#bce" },
  meta: { color: "#69f" },
  "meta string": { color: "#bce" },
  name: { bold: true, color: "#a7a" },
  number: { color: "#bce" },
  quote: { color: "#9c6", italic: true },
  regexp: { color: "#bce" },
  section: { bold: true, color: "#69f" },
  "selector-class": { bold: true, color: "#69f" },
  "selector-id": { bold: true, color: "#69f" },
  "selector-pseudo": { bold: true, color: "#69f", italic: true },
  "selector-tag": { bold: true, color: "#69f" },
  string: { color: "#bce" },
  strong: { bold: true },
  subst: { color: "#fff" },
  symbol: { color: "#d40" },
  tag: { color: "#fff" },
  "template-variable": { color: "#d40" },
  title: { color: "#d40" },
  "title.class": { bold: true, color: "#96c" },
  "title.function": { color: "#fff" },
  type: { bold: true, color: "#96c" },
  variable: { color: "#d40" },
};
