// Generated from highlight.js/styles/nord.css.

export default {
  attr: { color: "#8FBCBB" },
  attribute: { color: "#D8DEE9" },
  built_in: { color: "#8FBCBB" },
  bullet: { color: "#81A1C1" },
  class: { color: "#8FBCBB" },
  code: { color: "#8FBCBB" },
  comment: { color: "#4C566A" },
  default: { background: "#2E3440", color: "#D8DEE9" },
  doctag: { color: "#8FBCBB" },
  emphasis: { italic: true },
  formula: { color: "#8FBCBB" },
  function: { color: "#88C0D0" },
  keyword: { color: "#81A1C1" },
  literal: { color: "#81A1C1" },
  meta: { color: "#5E81AC" },
  "meta keyword": { color: "#5E81AC" },
  "meta string": { color: "#A3BE8C" },
  name: { color: "#81A1C1" },
  number: { color: "#B48EAD" },
  params: { color: "#D8DEE9" },
  property: { color: "#88C0D0" },
  quote: { color: "#4C566A" },
  regexp: { color: "#EBCB8B" },
  section: { color: "#88C0D0" },
  "selector-attr": { color: "#8FBCBB" },
  "selector-class": { color: "#8FBCBB" },
  "selector-id": { bold: true, color: "#8FBCBB" },
  "selector-pseudo": { color: "#88C0D0" },
  "selector-tag": { color: "#81A1C1" },
  string: { color: "#A3BE8C" },
  strong: { bold: true },
  subst: { color: "#D8DEE9" },
  symbol: { color: "#81A1C1" },
  tag: { color: "#81A1C1" },
  "template-tag": { color: "#5E81AC" },
  "template-variable": { color: "#D8DEE9" },
  title: { color: "#8FBCBB" },
  "title.function": { color: "#88C0D0" },
  type: { color: "#8FBCBB" },
  variable: { color: "#D8DEE9" },
};
