// Generated from highlight.js/styles/obsidian.css.

export default {
  addition: { color: "#8cbbad" },
  attribute: { color: "#668bb0" },
  built_in: { color: "#8cbbad" },
  bullet: { color: "#8cbbad" },
  "class title": { color: "#ffffff" },
  code: { color: "#ffffff" },
  comment: { color: "#818e96" },
  default: { background: "#282b2e", color: "#e0e2e4" },
  deletion: { color: "#818e96" },
  doctag: { bold: true },
  emphasis: { color: "#8cbbad" },
  keyword: { bold: true, color: "#93c763" },
  link: { color: "#d39745" },
  literal: { bold: true, color: "#93c763" },
  meta: { color: "#557182" },
  name: { bold: true, color: "#8cbbad" },
  number: { color: "#ffcd22" },
  quote: { color: "#818e96" },
  regexp: { color: "#d39745" },
  section: { bold: true, color: "#ffffff" },
  "selector-attr": { color: "#8cbbad" },
  "selector-class": { color: "#A082BD" },
  "selector-id": { color: "#93c763" },
  "selector-pseudo": { color: "#8cbbad" },
  "selector-tag": { bold: true, color: "#93c763" },
  string: { color: "#ec7600" },
  strong: { bold: true },
  subst: { color: "#8cbbad" },
  symbol: { color: "#ec7600" },
  tag: { color: "#8cbbad" },
  "template-tag": { color: "#8cbbad" },
  "template-variable": { color: "#8cbbad" },
  title: { bold: true },
  "title.class": { color: "#ffffff" },
  type: { bold: true, color: "#8cbbad" },
  variable: { color: "#8cbbad" },
};
