// Generated from highlight.js/styles/qtcreator-dark.css.

export default {
  addition: { color: "#ff55ff" },
  attribute: { color: "#ff5555" },
  built_in: { color: "#ff55ff" },
  bullet: { color: "#ff55ff" },
  "class title": { color: "#8888ff" },
  "code selector-class": { color: "#aaaaff" },
  comment: { color: "#55ffff" },
  default: { background: "#000000", color: "#aaaaaa" },
  deletion: { color: "#55ffff" },
  emphasis: { color: "#a8a8a2", italic: true },
  function: { color: "#ffff55" },
  keyword: { color: "#ffff55" },
  link: { color: "#ff55ff" },
  literal: { color: "#ff55ff" },
  meta: { color: "#55ffff" },
  name: { color: "#ffff55" },
  number: { color: "#ff55ff" },
  params: { color: "#8888ff" },
  quote: { color: "#ff55ff" },
  regexp: { color: "#ff55ff" },
  section: { color: "#ffff55" },
  "selector-attr": { color: "#ff55ff" },
  "selector-id": { color: "#ff55ff" },
  "selector-pseudo": { color: "#ff55ff" },
  "selector-tag": { color: "#ffff55" },
  string: { color: "#ff55ff" },
  strong: { color: "#a8a8a2" },
  stronge: { italic: true },
  subst: { color: "#aaaaaa" },
  symbol: { color: "#ffff55" },
  tag: { color: "#aaaaaa" },
  "template-tag": { color: "#ff55ff" },
  "template-variable": { color: "#ff55ff" },
  title: { color: "#aaaaaa" },
  "title.class": { color: "#8888ff" },
  type: { color: "#ff55ff", italic: true },
  variable: { color: "#8888ff" },
};
