// Generated from highlight.js/styles/rainbow.css.

export default {
  addition: { color: "#cc99cc" },
  attr: { color: "#81a2be" },
  attribute: { color: "#81a2be" },
  built_in: { color: "#b5bd68" },
  bullet: { color: "#f99157" },
  "class title": { color: "#ffcc66" },
  comment: { color: "#969896", italic: true },
  default: { background: "#474949", color: "#d1d9e1" },
  deletion: { color: "#dc322f" },
  doctag: { color: "#8abeb7" },
  emphasis: { italic: true },
  formula: { background: "#eee8d5" },
  keyword: { color: "#cc99cc" },
  link: { color: "#f99157" },
  literal: { color: "#cc99cc" },
  meta: { color: "#f99157" },
  name: { bold: true, color: "#b5bd68" },
  number: { color: "#f99157" },
  quote: { color: "#969896", italic: true },
  regexp: { color: "#8abeb7" },
  section: { bold: true, color: "#b5bd68" },
  "selector-attr": { color: "#f99157" },
  "selector-id": { color: "#ffcc66" },
  "selector-pseudo": { color: "#f99157" },
  "selector-tag": { color: "#cc99cc" },
  string: { color: "#8abeb7" },
  strong: { bold: true },
  subst: { color: "#f99157" },
  symbol: { color: "#f99157" },
  "template-variable": { color: "#ffcc66" },
  title: { color: "#b5bd68" },
  "title.class": { color: "#ffcc66" },
  type: { color: "#cc99cc" },
  variable: { color: "#ffcc66" },
};
