// Generated from highlight.js/styles/rose-pine.css.

export default {
  addition: { color: "#31748f" },
  attr: { color: "#c4a7e7" },
  attribute: { color: "#f6c177" },
  built_in: { color: "#f6c177" },
  bullet: { color: "#31748f" },
  "char.escape": { color: "#c4a7e7" },
  code: { color: "#ebbcba" },
  comment: { color: "#6e6a86" },
  default: { background: "#191724", color: "#6e6a86" },
  deletion: { color: "#eb6f92" },
  doctag: { color: "#eb6f92" },
  emphasis: { italic: true },
  formula: { color: "#ebbcba" },
  keyword: { color: "#c4a7e7" },
  link: { color: "#ebbcba" },
  literal: { color: "#ebbcba" },
  meta: { color: "#6e6a86" },
  name: { color: "#c4a7e7" },
  number: { color: "#ebbcba" },
  operator: { color: "#c4a7e7" },
  params: { color: "#ebbcba" },
  property: { color: "#9ccfd8" },
  punctuation: { color: "#e0def4" },
  quote: { color: "#31748f" },
  regexp: { color: "#eb6f92" },
  section: { color: "#ebbcba" },
  "selector-attr": { color: "#eb6f92" },
  "selector-class": { color: "#eb6f92" },
  "selector-id": { color: "#eb6f92" },
  "selector-pseudo": { color: "#eb6f92" },
  "selector-tag": { color: "#9ccfd8" },
  string: { color: "#31748f" },
  strong: { bold: true },
  subst: { color: "#9ccfd8" },
  symbol: { color: "#31748f" },
  tag: { color: "#eb6f92" },
  "template-tag": { color: "#eb6f92" },
  "template-variable": { color: "#ebbcba" },
  title: { color: "#9ccfd8" },
  "title.class": { color: "#9ccfd8" },
  "title.class.inherited": { color: "#9ccfd8" },
  "title.function": { color: "#9ccfd8" },
  type: { color: "#ebbcba" },
  variable: { color: "#ebbcba" },
  "variable.language": { color: "#eb6f92" },
};
