// Generated from highlight.js/styles/school-book.css.

export default {
  addition: { color: "#2c009f" },
  attribute: { color: "#2c009f" },
  built_in: { color: "#2c009f" },
  bullet: { color: "#2c009f" },
  comment: { color: "#e60415" },
  default: { background: "#f6f5b2", color: "#3e5915" },
  deletion: { color: "#e60415" },
  doctag: { bold: true },
  emphasis: { italic: true },
  keyword: { bold: true, color: "#005599" },
  link: { color: "#2c009f" },
  literal: { bold: true, color: "#005599" },
  meta: { color: "#e60415" },
  name: { bold: true },
  quote: { color: "#e60415" },
  section: { bold: true, color: "#2c009f" },
  "selector-id": { bold: true },
  "selector-tag": { bold: true, color: "#005599" },
  string: { color: "#2c009f" },
  strong: { bold: true },
  subst: { color: "#3e5915" },
  symbol: { color: "#2c009f" },
  "template-tag": { color: "#2c009f" },
  "template-variable": { color: "#2c009f" },
  title: { bold: true, color: "#2c009f" },
  type: { bold: true, color: "#2c009f" },
  variable: { color: "#2c009f" },
};
