// Generated from highlight.js/styles/srcery.css.

export default {
  addition: { color: "#98BC37" },
  attribute: { color: "#FBB829" },
  built_in: { color: "#FF5C8F" },
  bullet: { color: "#98BC37" },
  class: { color: "#0AAEB3" },
  code: { color: "#0AAEB3" },
  comment: { color: "#918175" },
  default: { background: "#1C1B19", color: "#FCE8C3" },
  deletion: { color: "#EF2F27" },
  emphasis: { italic: true },
  function: { color: "#FBB829" },
  keyword: { color: "#EF2F27" },
  link: { color: "#918175" },
  literal: { color: "#FCE8C3" },
  meta: { color: "#918175" },
  name: { color: "#FBB829" },
  number: { color: "#918175" },
  params: { color: "#FF5C8F" },
  property: { color: "#0AAEB3" },
  quote: { color: "#FCE8C3" },
  regexp: { color: "#98BC37" },
  section: { color: "#FBB829" },
  "selector-attr": { color: "#FBB829" },
  "selector-class": { color: "#FBB829" },
  "selector-id": { color: "#FBB829" },
  "selector-pseudo": { color: "#FBB829" },
  "selector-tag": { color: "#2C78BF" },
  string: { color: "#98BC37" },
  strong: { bold: true },
  subst: { color: "#FCE8C3" },
  symbol: { color: "#68A8E4" },
  "template-tag": { color: "#2C78BF" },
  "template-variable": { color: "#0AAEB3" },
  title: { color: "#FBB829" },
  type: { color: "#68A8E4" },
  variable: { color: "#0AAEB3" },
};
