// Generated from highlight.js/styles/stackoverflow-dark.css.

export default {
  addition: { color: "#76c490" },
  attr: { color: "#88aece" },
  attribute: { color: "#c59bc1" },
  built_in: { color: "#f08d49" },
  bullet: { color: "#cccccc" },
  code: { color: "#cccccc" },
  comment: { color: "#999999" },
  default: { background: "#1c1b1b", color: "#ffffff" },
  deletion: { color: "#de7176" },
  doctag: { color: "#88aece" },
  emphasis: { italic: true },
  keyword: { color: "#88aece" },
  link: { color: "#b5bd68" },
  literal: { color: "#f08d49" },
  meta: { color: "#88aece" },
  "meta keyword": { color: "#88aece" },
  "meta string": { color: "#b5bd68" },
  name: { color: "#f08d49" },
  number: { color: "#f08d49" },
  quote: { color: "#f08d49" },
  regexp: { color: "#b5bd68" },
  section: { color: "#88aece" },
  "selector-attr": { color: "#b5bd68" },
  "selector-class": { color: "#88aece" },
  "selector-id": { color: "#f08d49" },
  "selector-pseudo": { color: "#88aece" },
  "selector-tag": { color: "#88aece" },
  string: { color: "#b5bd68" },
  strong: { bold: true },
  subst: { color: "#ffffff" },
  symbol: { color: "#b5bd68" },
  "template-tag": { color: "#f08d49" },
  "template-variable": { color: "#b5bd68" },
  title: { color: "#f08d49" },
  type: { color: "#f08d49" },
  variable: { color: "#b5bd68" },
};
