// Generated from highlight.js/styles/sunburst.css.

export default {
  addition: { background: "#253b22", color: "#f8f8f8" },
  attribute: { color: "#cda869" },
  bullet: { color: "#3387cc" },
  "class title": { underline: true },
  comment: { color: "#aeaeae", italic: true },
  default: { background: "#000", color: "#f8f8f8" },
  deletion: { background: "#420e09", color: "#f8f8f8" },
  doctag: { underline: true },
  emphasis: { italic: true },
  formula: { background: "#0e2231", color: "#f8f8f8", italic: true },
  keyword: { color: "#e28964" },
  link: { color: "#e9c062" },
  meta: { color: "#8996a8" },
  name: { color: "#89bdff" },
  number: { color: "#3387cc" },
  params: { color: "#3e87e3" },
  quote: { color: "#aeaeae", italic: true },
  regexp: { color: "#e9c062" },
  section: { color: "#89bdff" },
  "selector-class": { color: "#9b703f" },
  "selector-id": { color: "#8b98ab" },
  "selector-tag": { color: "#e28964" },
  string: { color: "#65b042" },
  strong: { bold: true },
  subst: { color: "#daefa3" },
  symbol: { color: "#3387cc" },
  tag: { color: "#89bdff" },
  "template-variable": { color: "#3e87e3" },
  title: { color: "#89bdff" },
  "title.class": { underline: true },
  type: { color: "#e28964" },
  variable: { color: "#3e87e3" },
};
