// Generated from highlight.js/styles/vs2015.css.

export default {
  addition: { background: "#144212" },
  attr: { color: "#9CDCFE" },
  attribute: { color: "#9CDCFE" },
  built_in: { color: "#4EC9B0" },
  bullet: { color: "#D7BA7D" },
  class: { color: "#B8D7A3" },
  comment: { color: "#57A64A", italic: true },
  default: { background: "#1E1E1E", color: "#DCDCDC" },
  deletion: { background: "#600" },
  doctag: { color: "#608B4E" },
  emphasis: { italic: true },
  formula: { color: "#DCDCDC" },
  function: { color: "#DCDCDC" },
  keyword: { color: "#569CD6" },
  link: { color: "#569CD6", underline: true },
  literal: { color: "#569CD6" },
  meta: { color: "#9B9B9B" },
  "meta keyword": { color: "#9B9B9B" },
  "meta string": { color: "#D69D85" },
  name: { color: "#569CD6" },
  number: { color: "#B8D7A3" },
  params: { color: "#DCDCDC" },
  quote: { color: "#57A64A", italic: true },
  regexp: { color: "#9A5334" },
  section: { color: "#ffd700" },
  "selector-attr": { color: "#D7BA7D" },
  "selector-class": { color: "#D7BA7D" },
  "selector-id": { color: "#D7BA7D" },
  "selector-pseudo": { color: "#D7BA7D" },
  "selector-tag": { color: "#D7BA7D" },
  string: { color: "#D69D85" },
  strong: { bold: true },
  subst: { color: "#DCDCDC" },
  symbol: { color: "#569CD6" },
  tag: { color: "#9B9B9B" },
  "template-tag": { color: "#9A5334" },
  "template-variable": { color: "#BD63C5" },
  title: { color: "#DCDCDC" },
  type: { color: "#4EC9B0" },
  variable: { color: "#BD63C5" },
};
