// Generated from highlight.js/styles/xcode.css.

export default {
  addition: { background: "#baeeba" },
  attr: { color: "#836C28" },
  attribute: { color: "#aa0d91" },
  built_in: { color: "#5c2699" },
  bullet: { color: "#1c00cf" },
  "class title": { color: "#5c2699" },
  code: { color: "#c41a16" },
  comment: { color: "#007400" },
  default: { background: "#fff", color: "#000000" },
  deletion: { background: "#ffc8bd" },
  doctag: { bold: true },
  emphasis: { italic: true },
  formula: { background: "#eee", italic: true },
  keyword: { color: "#aa0d91" },
  link: { color: "#0E0EFF" },
  literal: { color: "#aa0d91" },
  meta: { color: "#643820" },
  "meta string": { color: "#c41a16" },
  name: { color: "#aa0d91" },
  number: { color: "#1c00cf" },
  params: { color: "#5c2699" },
  quote: { color: "#007400" },
  regexp: { color: "#0E0EFF" },
  section: { color: "#643820" },
  "selector-class": { color: "#9b703f" },
  "selector-id": { color: "#9b703f" },
  "selector-tag": { color: "#aa0d91" },
  string: { color: "#c41a16" },
  strong: { bold: true },
  subst: { color: "#000" },
  symbol: { color: "#1c00cf" },
  tag: { color: "#aa0d91" },
  "template-variable": { color: "#3F6E74" },
  title: { color: "#1c00cf" },
  "title.class": { color: "#5c2699" },
  type: { color: "#5c2699" },
  variable: { color: "#3F6E74" },
};
