// Generated from highlight.js/styles/xt256.css.

export default {
  attribute: { color: "#ff00ff" },
  built_in: { color: "#ff00ff" },
  bullet: { color: "#00ff00" },
  comment: { color: "#969896" },
  default: { background: "#000", color: "#eaeaea" },
  emphasis: { italic: true },
  keyword: { color: "#fff000" },
  link: { color: "#ff00ff" },
  literal: { color: "#ff0000" },
  meta: { color: "#fff" },
  name: { color: "#ff0000" },
  number: { color: "#ff0000" },
  params: { color: "#da0000" },
  quote: { color: "#00ffff" },
  regexp: { color: "#ff00ff" },
  section: { color: "#000fff" },
  "selector-class": { color: "#fff000" },
  "selector-id": { color: "#00ffff" },
  "selector-tag": { bold: true, color: "#000fff" },
  string: { color: "#00ff00" },
  strong: { bold: true },
  subst: { color: "#eaeaea" },
  symbol: { color: "#fff000" },
  tag: { color: "#000fff" },
  "template-variable": { bold: true, color: "#00ffff" },
  title: { bold: true, color: "#00ffff" },
  type: { color: "#eaeaea" },
  variable: { bold: true, color: "#00ffff" },
};
