import { applyStyle } from './style.js';
import { applyBackground } from './background.js';

/**
 * @param {string} token HTML token.
 * @returns {boolean} Whether the token opens a highlight span.
 */
const isOpenTag = (token) => /^<span\b/i.test(token);

/**
 * @param {string} token HTML token.
 * @returns {boolean} Whether the token closes a highlight span.
 */
const isCloseTag = (token) => /^<\/span\s*>$/i.test(token);

/**
 * @param {string} token HTML token.
 * @returns {boolean} Whether the token is an HTML tag.
 */
const isHtmlTag = (token) => /^<[^>]+>$/.test(token);

/**
 * Converts highlight.js class list into a dotted theme scope.
 *
 * @param {string[]} classNames Highlight.js class names from a span.
 * @returns {string} Theme scope.
 */
const getScope = (classNames) => classNames.map(normalizeScope).filter(Boolean).join('.');

/**
 * highlight.js uses trailing underscores for composed class names.
 *
 * @param {string} className Highlight.js class name.
 * @returns {string} Normalized scope part.
 */
const normalizeScope = (className) => className.replace(/^hljs-/, '').replace(/_+$/, '');

/**
 * Decodes the HTML entities.
 *
 * @param {string} value HTML text token.
 * @returns {string} Plain text token.
 */
const decodeHtmlEntities = (value) => value
.replace(/&amp;/g, '&')
.replace(/&lt;/g, '<')
.replace(/&gt;/g, '>')
.replace(/&quot;/g, '"')
.replace(/&#x27;/g, "'")
.replace(/&#39;/g, "'");

/**
 * @param {string} tag Opening span tag.
 * @returns {string[]} Class names from the tag.
 */
const getClassNames = (tag) => {
  const match = tag.match(/\sclass=(["'])(.*?)\1/i);

  return match ? match[2].trim().split(/\s+/) : [];
}

/**
 * Parses highlight.js HTML and renders text tokens through the current nested scope stack.
 *
 * @param {string} html Highlighted HTML generated by highlight.js.
 * @param {object} options Normalized terminal output options.
 * @returns {string} ANSI output.
 */
export function htmlToAnsi(html, options) {
  const theme = options.theme;
  const stack = [];
  const tokens = String(html).match(/<\/?span\b[^>]*>|<[^>]+>|[^<]+/gi) || [];

  let output = '';

  for (const token of tokens) {
    if (isOpenTag(token)) {
      const classNames = getClassNames(token);
      const scope = getScope(classNames);

      stack.push(scope);
      continue;
    }

    if (isCloseTag(token)) {
      stack.pop();
      continue;
    }

    if (isHtmlTag(token)) {
      continue;
    }

    output += applyStyle(decodeHtmlEntities(token), stack, theme);
  }

  return applyBackground(output, options);
}
